# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\achill123\Desktop\PharmaProject\designpharma.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1312, 897)
        MainWindow.setMinimumSize(QtCore.QSize(1312, 897))
        MainWindow.setMaximumSize(QtCore.QSize(1312, 897))
        MainWindow.setStyleSheet(_fromUtf8("background:white;"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1331, 877))
        self.tabWidget.setStyleSheet(_fromUtf8("\n"
"\n"
"background:qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(32, 221, 225, 179), stop:0.497326 rgba(0, 0, 0, 147), stop:1 rgba(0, 169, 255, 147));\n"
""))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Dispensary_tab = QtGui.QWidget()
        self.Dispensary_tab.setObjectName(_fromUtf8("Dispensary_tab"))
        self.BPrint = QtGui.QPushButton(self.Dispensary_tab)
        self.BPrint.setGeometry(QtCore.QRect(658, 761, 321, 28))
        self.BPrint.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BPrint.setStyleSheet(_fromUtf8("background-color:rgb(75, 226, 226);\n"
"alternate-background-color: rgb(75, 226, 226);\n"
"color:black;\n"
"font:bold;"))
        self.BPrint.setObjectName(_fromUtf8("BPrint"))
        self.BNext = QtGui.QPushButton(self.Dispensary_tab)
        self.BNext.setGeometry(QtCore.QRect(982, 761, 321, 28))
        self.BNext.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BNext.setStyleSheet(_fromUtf8("color:white;font:bold;"))
        self.BNext.setObjectName(_fromUtf8("BNext"))
        self.BLookup = QtGui.QPushButton(self.Dispensary_tab)
        self.BLookup.setGeometry(QtCore.QRect(335, 791, 321, 28))
        self.BLookup.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BLookup.setStyleSheet(_fromUtf8("background-color:rgb(75, 226, 226);\n"
"alternate-background-color: rgb(75, 226, 226);\n"
"color:black;\n"
"font:bold;"))
        self.BLookup.setObjectName(_fromUtf8("BLookup"))
        self.BCalculator = QtGui.QPushButton(self.Dispensary_tab)
        self.BCalculator.setGeometry(QtCore.QRect(335, 731, 321, 28))
        self.BCalculator.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BCalculator.setStyleSheet(_fromUtf8("background-color:rgb(75, 226, 226);\n"
"alternate-background-color: rgb(75, 226, 226);\n"
"color:black;\n"
"font:bold;"))
        self.BCalculator.setObjectName(_fromUtf8("BCalculator"))
        self.groupBox_2 = QtGui.QGroupBox(self.Dispensary_tab)
        self.groupBox_2.setGeometry(QtCore.QRect(880, 420, 411, 271))
        self.groupBox_2.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.groupBox_2.setStyleSheet(_fromUtf8("background:transparent;\n"
"color:white;font:bold;"))
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(22, 21, 41, 16))
        self.label_4.setStyleSheet(_fromUtf8("color:white;font:bold;\n"
"background:transparent;"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(22, 50, 23, 16))
        self.label_5.setStyleSheet(_fromUtf8("\n"
"color:white;font:bold;"))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(22, 79, 76, 16))
        self.label_6.setStyleSheet(_fromUtf8("color: rgb(154, 0, 0);\n"
"background:transparent;\n"
"color:white;font:bold;"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(22, 108, 71, 16))
        self.label_7.setStyleSheet(_fromUtf8("background:transparent;\n"
"color:white;font:bold;"))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(22, 137, 61, 16))
        self.label_8.setStyleSheet(_fromUtf8("background:transparent;color: rgb(154, 0, 0);\n"
"color:white;font:bold;"))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(11, 166, 111, 16))
        self.label_9.setStyleSheet(_fromUtf8("color:white;font:bold;\n"
"background:transparent;"))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(22, 195, 61, 16))
        self.label_10.setStyleSheet(_fromUtf8("color:white;font:bold;\n"
"background:transparent;"))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.RTotal = QtGui.QLineEdit(self.groupBox_2)
        self.RTotal.setGeometry(QtCore.QRect(121, 21, 137, 22))
        self.RTotal.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.RTotal.setStyleSheet(_fromUtf8("background-color:white;\n"
"color: rgb(154, 0, 0);"))
        self.RTotal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.RTotal.setObjectName(_fromUtf8("RTotal"))
        self.RNhf = QtGui.QLineEdit(self.groupBox_2)
        self.RNhf.setGeometry(QtCore.QRect(121, 50, 137, 22))
        self.RNhf.setStyleSheet(_fromUtf8("background-color:white;\n"
"color:red"))
        self.RNhf.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.RNhf.setObjectName(_fromUtf8("RNhf"))
        self.RDrug = QtGui.QLineEdit(self.groupBox_2)
        self.RDrug.setGeometry(QtCore.QRect(121, 79, 137, 22))
        self.RDrug.setStyleSheet(_fromUtf8("background-color:white;\n"
"color: rgb(154, 0, 0);"))
        self.RDrug.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.RDrug.setObjectName(_fromUtf8("RDrug"))
        self.R31 = QtGui.QLineEdit(self.groupBox_2)
        self.R31.setGeometry(QtCore.QRect(122, 109, 65, 22))
        self.R31.setStyleSheet(_fromUtf8("background-color:white;\n"
"color:black;"))
        self.R31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.R31.setObjectName(_fromUtf8("R31"))
        self.R32 = QtGui.QLineEdit(self.groupBox_2)
        self.R32.setGeometry(QtCore.QRect(193, 109, 65, 22))
        self.R32.setStyleSheet(_fromUtf8("background-color:white;\n"
"color:black;"))
        self.R32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.R32.setObjectName(_fromUtf8("R32"))
        self.RCo = QtGui.QLineEdit(self.groupBox_2)
        self.RCo.setGeometry(QtCore.QRect(121, 137, 137, 22))
        self.RCo.setStyleSheet(_fromUtf8("background-color:white;\n"
"color: rgb(0, 0, 166);"))
        self.RCo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.RCo.setObjectName(_fromUtf8("RCo"))
        self.RAgreed = QtGui.QLineEdit(self.groupBox_2)
        self.RAgreed.setGeometry(QtCore.QRect(121, 166, 137, 22))
        self.RAgreed.setStyleSheet(_fromUtf8("background-color:rgb(75, 226, 226);\n"
"alternate-background-color: rgb(75, 226, 226);\n"
"color:black;\n"
""))
        self.RAgreed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.RAgreed.setObjectName(_fromUtf8("RAgreed"))
        self.RDiscount = QtGui.QComboBox(self.groupBox_2)
        self.RDiscount.setGeometry(QtCore.QRect(121, 195, 68, 22))
        self.RDiscount.setStyleSheet(_fromUtf8("background-color:white;\n"
"color:red"))
        self.RDiscount.setObjectName(_fromUtf8("RDiscount"))
        self.RDiscount.addItem(_fromUtf8(""))
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(221, 200, 53, 16))
        self.label_11.setStyleSheet(_fromUtf8("background:transparent;"))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(19, 230, 381, 31))
        self.label_12.setStyleSheet(_fromUtf8("color: rgb(104, 104, 104);\n"
"\n"
"background:transparent;\n"
"color: rgb(154, 0, 0);\n"
"\n"
"color:rgba(0, 0, 0, 147);\n"
"color:white;\n"
"font: 75 10pt \"Unispace\";"))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.ApplyMain = QtGui.QPushButton(self.groupBox_2)
        self.ApplyMain.setGeometry(QtCore.QRect(305, 5, 93, 21))
        self.ApplyMain.setStyleSheet(_fromUtf8("background-color:rgb(75, 226, 226);\n"
"alternate-background-color: rgb(75, 226, 226);\n"
"color:black;\n"
""))
        self.ApplyMain.setObjectName(_fromUtf8("ApplyMain"))
        self.BQuote = QtGui.QPushButton(self.Dispensary_tab)
        self.BQuote.setGeometry(QtCore.QRect(658, 791, 321, 28))
        self.BQuote.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BQuote.setStyleSheet(_fromUtf8("background-color:rgb(75, 226, 226);\n"
"alternate-background-color: rgb(75, 226, 226);\n"
"color:black;\n"
"font:bold;"))
        self.BQuote.setObjectName(_fromUtf8("BQuote"))
        self.line = QtGui.QFrame(self.Dispensary_tab)
        self.line.setGeometry(QtCore.QRect(0, 710, 1301, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.BInternet = QtGui.QPushButton(self.Dispensary_tab)
        self.BInternet.setGeometry(QtCore.QRect(658, 731, 321, 28))
        self.BInternet.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BInternet.setStyleSheet(_fromUtf8("background-color:rgb(75, 226, 226);\n"
"alternate-background-color: rgb(75, 226, 226);\n"
"color:black;\n"
"font:bold;"))
        self.BInternet.setObjectName(_fromUtf8("BInternet"))
        self.groupBox = QtGui.QGroupBox(self.Dispensary_tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 420, 411, 271))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.groupBox.setPalette(palette)
        self.groupBox.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setStyleSheet(_fromUtf8("background:transparent;\n"
"font:bold;\n"
"color:white;"))
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(11, 41, 41, 16))
        self.label.setStyleSheet(_fromUtf8("background:transparent;"))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(11, 110, 51, 16))
        self.label_2.setStyleSheet(_fromUtf8("color: white;\n"
"font: 90 bold 8pt \"MS Shell Dlg 2\";\n"
"background:transparent;"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(11, 178, 51, 16))
        self.label_3.setStyleSheet(_fromUtf8("color: white;\n"
"font: 90 bold 8pt \"MS Shell Dlg 2\";\n"
"background:transparent;"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.PName = QtGui.QLineEdit(self.groupBox)
        self.PName.setGeometry(QtCore.QRect(60, 40, 221, 22))
        self.PName.setStyleSheet(_fromUtf8("background-color:white;\n"
"color:black;\n"
"font:bold;"))
        self.PName.setObjectName(_fromUtf8("PName"))
        self.PSource = QtGui.QComboBox(self.groupBox)
        self.PSource.setGeometry(QtCore.QRect(60, 177, 221, 22))
        self.PSource.setStyleSheet(_fromUtf8("background-color:white;\n"
"color:black;\n"
"font:bold;"))
        self.PSource.setObjectName(_fromUtf8("PSource"))
        self.PSource.addItem(_fromUtf8(""))
        self.PSource.addItem(_fromUtf8(""))
        self.PDoctor = QtGui.QComboBox(self.groupBox)
        self.PDoctor.setGeometry(QtCore.QRect(60, 110, 221, 22))
        self.PDoctor.setStyleSheet(_fromUtf8("background:white;\n"
"color:black;\n"
"font:bold;"))
        self.PDoctor.setObjectName(_fromUtf8("PDoctor"))
        self.groupBox_3 = QtGui.QGroupBox(self.Dispensary_tab)
        self.groupBox_3.setGeometry(QtCore.QRect(445, 420, 411, 271))
        self.groupBox_3.setStyleSheet(_fromUtf8("background:transparent;\n"
"font:bold;\n"
"color:white;font:bold;"))
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.RxN = QtGui.QLineEdit(self.groupBox_3)
        self.RxN.setGeometry(QtCore.QRect(110, 43, 134, 22))
        self.RxN.setStyleSheet(_fromUtf8("background-color: white;\n"
"color:black;\n"
"font:bold;\n"
"\n"
""))
        self.RxN.setText(_fromUtf8(""))
        self.RxN.setObjectName(_fromUtf8("RxN"))
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(67, 45, 36, 16))
        self.label_13.setStyleSheet(_fromUtf8("font:bold;\n"
"background:transparent;\n"
"color:white;"))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.NewScript = QtGui.QPushButton(self.groupBox_3)
        self.NewScript.setGeometry(QtCore.QRect(250, 40, 93, 28))
        self.NewScript.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.NewScript.setStyleSheet(_fromUtf8("background-color:rgb(75, 226, 226);\n"
"alternate-background-color: rgb(75, 226, 226);\n"
"color:black;\n"
""))
        self.NewScript.setObjectName(_fromUtf8("NewScript"))
        self.label_14 = QtGui.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(60, 120, 311, 71))
        self.label_14.setStyleSheet(_fromUtf8("color: rgb(104, 104, 104);\n"
"font: 75 italic 10pt \\\"8514oem\\\";\n"
"background:transparent;\n"
"color:white;\n"
"font: 75 italic 13pt  \"Unispace\";"))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.MyDate = QtGui.QLabel(self.Dispensary_tab)
        self.MyDate.setGeometry(QtCore.QRect(1115, 5, 171, 16))
        self.MyDate.setStyleSheet(_fromUtf8("color:rgb(163, 8, 29);\n"
"background:transparent;\n"
"font:bold;\n"
"color:white;"))
        self.MyDate.setObjectName(_fromUtf8("MyDate"))
        self.BClose = QtGui.QPushButton(self.Dispensary_tab)
        self.BClose.setGeometry(QtCore.QRect(982, 731, 321, 28))
        self.BClose.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BClose.setStyleSheet(_fromUtf8("background-color:rgb(75, 226, 226);\n"
"alternate-background-color: rgb(75, 226, 226);\n"
"color:black;\n"
"font:bold;"))
        self.BClose.setObjectName(_fromUtf8("BClose"))
        self.MainTableX = QtGui.QTableWidget(self.Dispensary_tab)
        self.MainTableX.setGeometry(QtCore.QRect(10, 30, 1291, 381))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(32, 221, 225, 179))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 221, 225, 179))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 221, 225, 179))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 221, 225, 179))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 221, 225, 179))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 221, 225, 179))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.MainTableX.setPalette(palette)
        self.MainTableX.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.MainTableX.setStyleSheet(_fromUtf8("\n"
"background:rgba(32, 221, 225, 179);\n"
"alternate-background-color:rgba(0, 0, 0, 147);\n"
"font:bold;\n"
""))
        self.MainTableX.setFrameShadow(QtGui.QFrame.Sunken)
        self.MainTableX.setLineWidth(1)
        self.MainTableX.setMidLineWidth(0)
        self.MainTableX.setAlternatingRowColors(True)
        self.MainTableX.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.MainTableX.setRowCount(20)
        self.MainTableX.setObjectName(_fromUtf8("MainTableX"))
        self.MainTableX.setColumnCount(17)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(161, 193, 56))
        self.MainTableX.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        item.setFont(font)
        self.MainTableX.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.MainTableX.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.MainTableX.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.MainTableX.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.MainTableX.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.MainTableX.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.MainTableX.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.MainTableX.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.MainTableX.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.MainTableX.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.MainTableX.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.MainTableX.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.MainTableX.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.MainTableX.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.MainTableX.setHorizontalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.MainTableX.setHorizontalHeaderItem(16, item)
        self.MainTableX.horizontalHeader().setCascadingSectionResizes(False)
        self.MainTableX.horizontalHeader().setSortIndicatorShown(False)
        self.MainTableX.horizontalHeader().setStretchLastSection(False)
        self.MainTableX.verticalHeader().setVisible(False)
        self.BLabel = QtGui.QPushButton(self.Dispensary_tab)
        self.BLabel.setGeometry(QtCore.QRect(11, 791, 321, 28))
        self.BLabel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BLabel.setStyleSheet(_fromUtf8("background-color:rgb(75, 226, 226);\n"
"alternate-background-color: rgb(75, 226, 226);\n"
"color:black;\n"
"font:bold;"))
        self.BLabel.setObjectName(_fromUtf8("BLabel"))
        self.BDrugs = QtGui.QPushButton(self.Dispensary_tab)
        self.BDrugs.setGeometry(QtCore.QRect(11, 761, 321, 28))
        self.BDrugs.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BDrugs.setStyleSheet(_fromUtf8("background-color:rgb(75, 226, 226);\n"
"alternate-background-color: rgb(75, 226, 226);\n"
"color:black;\n"
"font:bold;"))
        self.BDrugs.setObjectName(_fromUtf8("BDrugs"))
        self.BPatient = QtGui.QPushButton(self.Dispensary_tab)
        self.BPatient.setGeometry(QtCore.QRect(335, 761, 321, 28))
        self.BPatient.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BPatient.setStyleSheet(_fromUtf8("background-color:rgb(75, 226, 226);\n"
"alternate-background-color: rgb(75, 226, 226);\n"
"color:black;\n"
"font:bold;"))
        self.BPatient.setObjectName(_fromUtf8("BPatient"))
        self.BReversal = QtGui.QPushButton(self.Dispensary_tab)
        self.BReversal.setGeometry(QtCore.QRect(11, 731, 321, 28))
        self.BReversal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BReversal.setStyleSheet(_fromUtf8("background-color:rgb(75, 226, 226);\n"
"alternate-background-color: rgb(75, 226, 226);\n"
"color:black;\n"
"font:bold;"))
        self.BReversal.setFlat(False)
        self.BReversal.setObjectName(_fromUtf8("BReversal"))
        self.BDelete = QtGui.QPushButton(self.Dispensary_tab)
        self.BDelete.setGeometry(QtCore.QRect(982, 791, 321, 28))
        self.BDelete.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BDelete.setStyleSheet(_fromUtf8("background-color:rgb(75, 226, 226);\n"
"alternate-background-color: rgb(75, 226, 226);\n"
"color:black;\n"
"font:bold;"))
        self.BDelete.setObjectName(_fromUtf8("BDelete"))
        self.AddPresc = QtGui.QPushButton(self.Dispensary_tab)
        self.AddPresc.setGeometry(QtCore.QRect(10, 8, 93, 20))
        self.AddPresc.setStyleSheet(_fromUtf8("color:white;\n"
"font:bold;"))
        self.AddPresc.setObjectName(_fromUtf8("AddPresc"))
        self.DeletePresc = QtGui.QPushButton(self.Dispensary_tab)
        self.DeletePresc.setGeometry(QtCore.QRect(105, 8, 93, 20))
        self.DeletePresc.setStyleSheet(_fromUtf8("color:white;font:bold;"))
        self.DeletePresc.setObjectName(_fromUtf8("DeletePresc"))
        self.tabWidget.addTab(self.Dispensary_tab, _fromUtf8(""))
        self.Sales_Tab = QtGui.QWidget()
        self.Sales_Tab.setObjectName(_fromUtf8("Sales_Tab"))
        self.SHTable1 = QtGui.QTableWidget(self.Sales_Tab)
        self.SHTable1.setGeometry(QtCore.QRect(12, 70, 1301, 581))
        self.SHTable1.setStyleSheet(_fromUtf8("background:rgba(32, 221, 225, 179);\n"
"alternate-background-color:rgba(0, 0, 0, 147);\n"
"\n"
"font:bold;\n"
""))
        self.SHTable1.setAlternatingRowColors(True)
        self.SHTable1.setRowCount(30)
        self.SHTable1.setObjectName(_fromUtf8("SHTable1"))
        self.SHTable1.setColumnCount(20)
        item = QtGui.QTableWidgetItem()
        self.SHTable1.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.SHTable1.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.SHTable1.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.SHTable1.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.SHTable1.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.SHTable1.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.SHTable1.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.SHTable1.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.SHTable1.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.SHTable1.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.SHTable1.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.SHTable1.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.SHTable1.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.SHTable1.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.SHTable1.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.SHTable1.setHorizontalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.SHTable1.setHorizontalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        self.SHTable1.setHorizontalHeaderItem(17, item)
        item = QtGui.QTableWidgetItem()
        self.SHTable1.setHorizontalHeaderItem(18, item)
        item = QtGui.QTableWidgetItem()
        self.SHTable1.setHorizontalHeaderItem(19, item)
        self.SHTable2 = QtGui.QTableWidget(self.Sales_Tab)
        self.SHTable2.setGeometry(QtCore.QRect(300, 650, 701, 161))
        self.SHTable2.setStyleSheet(_fromUtf8("background:rgba(32, 221, 225, 179);\n"
"font:bold,"))
        self.SHTable2.setObjectName(_fromUtf8("SHTable2"))
        self.SHTable2.setColumnCount(7)
        self.SHTable2.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.SHTable2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.SHTable2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.SHTable2.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.SHTable2.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.SHTable2.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.SHTable2.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.SHTable2.setHorizontalHeaderItem(6, item)
        self.SHPrint = QtGui.QPushButton(self.Sales_Tab)
        self.SHPrint.setGeometry(QtCore.QRect(1208, 790, 93, 28))
        self.SHPrint.setStyleSheet(_fromUtf8("background-color:rgb(75, 226, 226);\n"
"alternate-background-color: rgb(75, 226, 226);\n"
"color:black;\n"
"font:bold;"))
        self.SHPrint.setObjectName(_fromUtf8("SHPrint"))
        self.label_15 = QtGui.QLabel(self.Sales_Tab)
        self.label_15.setGeometry(QtCore.QRect(20, 14, 201, 41))
        self.label_15.setStyleSheet(_fromUtf8("color: blue;\n"
"font: 87 bold 11pt \"Arial Black\";\n"
"background:transparent;\n"
"font: 75 bold 14pt  \"Unispace\";"))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.groupBox_4 = QtGui.QGroupBox(self.Sales_Tab)
        self.groupBox_4.setGeometry(QtCore.QRect(820, 2, 481, 61))
        self.groupBox_4.setStyleSheet(_fromUtf8("background:transparent;\n"
"color:white;\n"
"font:bold;"))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.SHDate1 = QtGui.QDateEdit(self.groupBox_4)
        self.SHDate1.setGeometry(QtCore.QRect(10, 24, 110, 22))
        self.SHDate1.setStyleSheet(_fromUtf8("background-color:white;\n"
"color:black"))
        self.SHDate1.setObjectName(_fromUtf8("SHDate1"))
        self.SHDate2 = QtGui.QDateEdit(self.groupBox_4)
        self.SHDate2.setGeometry(QtCore.QRect(160, 24, 110, 22))
        self.SHDate2.setStyleSheet(_fromUtf8("background-color:white;\n"
"color:black;"))
        self.SHDate2.setObjectName(_fromUtf8("SHDate2"))
        self.label_16 = QtGui.QLabel(self.groupBox_4)
        self.label_16.setGeometry(QtCore.QRect(130, 26, 21, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.SHRefresh = QtGui.QPushButton(self.groupBox_4)
        self.SHRefresh.setGeometry(QtCore.QRect(280, 20, 93, 28))
        self.SHRefresh.setStyleSheet(_fromUtf8("background-color:rgb(75, 226, 226);\n"
"alternate-background-color: rgb(75, 226, 226);\n"
"color:black;\n"
"font:bold;\n"
""))
        self.SHRefresh.setObjectName(_fromUtf8("SHRefresh"))
        self.SHClose = QtGui.QPushButton(self.groupBox_4)
        self.SHClose.setGeometry(QtCore.QRect(380, 20, 93, 28))
        self.SHClose.setStyleSheet(_fromUtf8("background-color:rgb(75, 226, 226);\n"
"alternate-background-color: rgb(75, 226, 226);\n"
"color:black;\n"
"font:bold;\n"
""))
        self.SHClose.setObjectName(_fromUtf8("SHClose"))
        self.SMy_Date = QtGui.QLabel(self.Sales_Tab)
        self.SMy_Date.setGeometry(QtCore.QRect(1115, 660, 171, 16))
        self.SMy_Date.setStyleSheet(_fromUtf8("background:transparent;\n"
"color:white;\n"
"font:bold;\n"
""))
        self.SMy_Date.setObjectName(_fromUtf8("SMy_Date"))
        self.tabWidget.addTab(self.Sales_Tab, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 10, 1281, 81))
        self.groupBox_5.setStyleSheet(_fromUtf8("background:transparent;"))
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setFlat(False)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.label_17 = QtGui.QLabel(self.groupBox_5)
        self.label_17.setGeometry(QtCore.QRect(30, 10, 261, 51))
        self.label_17.setStyleSheet(_fromUtf8("color: red;\n"
"\n"
"background:transparent;\n"
"font: 75 bold 14pt  \"Unispace\";"))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.PHClose = QtGui.QPushButton(self.groupBox_5)
        self.PHClose.setGeometry(QtCore.QRect(1170, 20, 93, 28))
        self.PHClose.setStyleSheet(_fromUtf8("background-color:rgb(75, 226, 226);\n"
"alternate-background-color: rgb(75, 226, 226);\n"
"color:black;\n"
"font:bold;\n"
""))
        self.PHClose.setObjectName(_fromUtf8("PHClose"))
        self.label_18 = QtGui.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(30, 110, 53, 16))
        self.label_18.setStyleSheet(_fromUtf8("color:blue;\n"
"font:bold;\n"
"background:transparent;"))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.PHProduct = QtGui.QComboBox(self.tab)
        self.PHProduct.setGeometry(QtCore.QRect(88, 110, 211, 22))
        self.PHProduct.setStyleSheet(_fromUtf8("background:white;"))
        self.PHProduct.setObjectName(_fromUtf8("PHProduct"))
        self.PHPrint = QtGui.QPushButton(self.tab)
        self.PHPrint.setGeometry(QtCore.QRect(1190, 110, 93, 28))
        self.PHPrint.setStyleSheet(_fromUtf8("background-color:rgb(75, 226, 226);\n"
"alternate-background-color: rgb(75, 226, 226);\n"
"color:black;\n"
"font:bold;"))
        self.PHPrint.setObjectName(_fromUtf8("PHPrint"))
        self.PHTable = QtGui.QTableWidget(self.tab)
        self.PHTable.setGeometry(QtCore.QRect(10, 150, 1281, 641))
        self.PHTable.setStyleSheet(_fromUtf8("background:rgba(32, 221, 225, 179);\n"
"alternate-background-color:rgba(0, 0, 0, 147);\n"
"font:bold;"))
        self.PHTable.setAlternatingRowColors(True)
        self.PHTable.setRowCount(30)
        self.PHTable.setObjectName(_fromUtf8("PHTable"))
        self.PHTable.setColumnCount(13)
        item = QtGui.QTableWidgetItem()
        self.PHTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.PHTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.PHTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.PHTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.PHTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.PHTable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.PHTable.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.PHTable.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.PHTable.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.PHTable.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.PHTable.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.PHTable.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.PHTable.setHorizontalHeaderItem(12, item)
        self.PHTotals = QtGui.QLabel(self.tab)
        self.PHTotals.setGeometry(QtCore.QRect(30, 800, 53, 16))
        self.PHTotals.setStyleSheet(_fromUtf8("background:transparent;\n"
"color:white;\n"
"font:bold;"))
        self.PHTotals.setObjectName(_fromUtf8("PHTotals"))
        self.PHQty = QtGui.QLabel(self.tab)
        self.PHQty.setGeometry(QtCore.QRect(160, 800, 53, 16))
        self.PHQty.setStyleSheet(_fromUtf8("background:transparent;\n"
"color:white;\n"
"font:bold;"))
        self.PHQty.setObjectName(_fromUtf8("PHQty"))
        self.PHValue = QtGui.QLabel(self.tab)
        self.PHValue.setGeometry(QtCore.QRect(260, 800, 53, 16))
        self.PHValue.setStyleSheet(_fromUtf8("background:transparent;\n"
"color:white;\n"
"font:bold;"))
        self.PHValue.setObjectName(_fromUtf8("PHValue"))
        self.PMy_Date = QtGui.QLabel(self.tab)
        self.PMy_Date.setGeometry(QtCore.QRect(1115, 800, 171, 16))
        self.PMy_Date.setStyleSheet(_fromUtf8("background:transparent;\n"
"color:white;font:bold;"))
        self.PMy_Date.setObjectName(_fromUtf8("PMy_Date"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 8, 1281, 71))
        self.groupBox_6.setTitle(_fromUtf8(""))
        self.groupBox_6.setFlat(False)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.label_19 = QtGui.QLabel(self.groupBox_6)
        self.label_19.setGeometry(QtCore.QRect(16, 27, 53, 16))
        self.label_19.setStyleSheet(_fromUtf8("background:transparent;\n"
"font:bold;\n"
"font: 75 bold 8pt  \"Unispace\";"))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.DrugsList = QtGui.QLineEdit(self.groupBox_6)
        self.DrugsList.setGeometry(QtCore.QRect(70, 23, 191, 22))
        self.DrugsList.setStyleSheet(_fromUtf8("background-color:white;\n"
"font:bold;\n"
"color:black;\n"
""))
        self.DrugsList.setObjectName(_fromUtf8("DrugsList"))
        self.SearchDrugs = QtGui.QPushButton(self.groupBox_6)
        self.SearchDrugs.setGeometry(QtCore.QRect(420, 20, 93, 28))
        self.SearchDrugs.setStyleSheet(_fromUtf8("color:white;\n"
"font:bold;\n"
"font: 75 bold 8pt  \"Unispace\";"))
        self.SearchDrugs.setObjectName(_fromUtf8("SearchDrugs"))
        self.EditDrugs = QtGui.QPushButton(self.groupBox_6)
        self.EditDrugs.setGeometry(QtCore.QRect(520, 20, 93, 28))
        self.EditDrugs.setStyleSheet(_fromUtf8("color:white;\n"
"font:bold;\n"
"font: 75 bold 8pt  \"Unispace\";"))
        self.EditDrugs.setObjectName(_fromUtf8("EditDrugs"))
        self.RefreshDrugs = QtGui.QPushButton(self.groupBox_6)
        self.RefreshDrugs.setGeometry(QtCore.QRect(720, 20, 93, 28))
        self.RefreshDrugs.setStyleSheet(_fromUtf8("color:white;\n"
"font:bold;\n"
"font: 75 bold 8pt  \"Unispace\";"))
        self.RefreshDrugs.setObjectName(_fromUtf8("RefreshDrugs"))
        self.CloseDrugs = QtGui.QPushButton(self.groupBox_6)
        self.CloseDrugs.setGeometry(QtCore.QRect(1180, 20, 93, 28))
        self.CloseDrugs.setStyleSheet(_fromUtf8("\n"
"color:white;\n"
"font:bold;\n"
"font: 75 bold 8pt  \"Unispace\";"))
        self.CloseDrugs.setObjectName(_fromUtf8("CloseDrugs"))
        self.NewDrugs = QtGui.QPushButton(self.groupBox_6)
        self.NewDrugs.setGeometry(QtCore.QRect(1080, 20, 93, 28))
        self.NewDrugs.setStyleSheet(_fromUtf8("\n"
"color:white;\n"
"font:bold;\n"
"font: 75 bold 8pt  \"Unispace\";"))
        self.NewDrugs.setObjectName(_fromUtf8("NewDrugs"))
        self.DeleteDrugs = QtGui.QPushButton(self.groupBox_6)
        self.DeleteDrugs.setGeometry(QtCore.QRect(620, 20, 93, 28))
        self.DeleteDrugs.setStyleSheet(_fromUtf8("color:white;\n"
"font:bold;\n"
"font: 75 bold 8pt  \"Unispace\";"))
        self.DeleteDrugs.setObjectName(_fromUtf8("DeleteDrugs"))
        self.SelectDrug = QtGui.QPushButton(self.groupBox_6)
        self.SelectDrug.setGeometry(QtCore.QRect(980, 20, 93, 28))
        self.SelectDrug.setStyleSheet(_fromUtf8("color:white;\n"
"font:bold;\n"
"font: 75 bold 8pt  \"Unispace\";"))
        self.SelectDrug.setObjectName(_fromUtf8("SelectDrug"))
        self.SearchByWhat = QtGui.QComboBox(self.groupBox_6)
        self.SearchByWhat.setGeometry(QtCore.QRect(270, 20, 142, 28))
        self.SearchByWhat.setStyleSheet(_fromUtf8("\n"
"background-color: rgb(0, 240, 240);\n"
"font:bold;\n"
"font: 75 bold 8pt  \"Unispace\";"))
        self.SearchByWhat.setObjectName(_fromUtf8("SearchByWhat"))
        self.SearchByWhat.addItem(_fromUtf8(""))
        self.SearchByWhat.addItem(_fromUtf8(""))
        self.SearchByWhat.addItem(_fromUtf8(""))
        self.DrugsTable = QtGui.QTableWidget(self.tab_2)
        self.DrugsTable.setGeometry(QtCore.QRect(10, 80, 1281, 701))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(32, 221, 225, 179))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 221, 225, 179))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 221, 225, 179))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 221, 225, 179))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 221, 225, 179))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 221, 225, 179))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.DrugsTable.setPalette(palette)
        self.DrugsTable.setStyleSheet(_fromUtf8("background:rgba(32, 221, 225, 179);\n"
"alternate-background-color:rgba(0, 0, 0, 147);\n"
"font:bold;"))
        self.DrugsTable.setAlternatingRowColors(True)
        self.DrugsTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.DrugsTable.setShowGrid(True)
        self.DrugsTable.setGridStyle(QtCore.Qt.SolidLine)
        self.DrugsTable.setWordWrap(True)
        self.DrugsTable.setCornerButtonEnabled(True)
        self.DrugsTable.setRowCount(0)
        self.DrugsTable.setObjectName(_fromUtf8("DrugsTable"))
        self.DrugsTable.setColumnCount(31)
        item = QtGui.QTableWidgetItem()
        self.DrugsTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.DrugsTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.DrugsTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.DrugsTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.DrugsTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.DrugsTable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.DrugsTable.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.DrugsTable.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.DrugsTable.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.DrugsTable.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.DrugsTable.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.DrugsTable.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.DrugsTable.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.DrugsTable.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.DrugsTable.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.DrugsTable.setHorizontalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.DrugsTable.setHorizontalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        self.DrugsTable.setHorizontalHeaderItem(17, item)
        item = QtGui.QTableWidgetItem()
        self.DrugsTable.setHorizontalHeaderItem(18, item)
        item = QtGui.QTableWidgetItem()
        self.DrugsTable.setHorizontalHeaderItem(19, item)
        item = QtGui.QTableWidgetItem()
        self.DrugsTable.setHorizontalHeaderItem(20, item)
        item = QtGui.QTableWidgetItem()
        self.DrugsTable.setHorizontalHeaderItem(21, item)
        item = QtGui.QTableWidgetItem()
        self.DrugsTable.setHorizontalHeaderItem(22, item)
        item = QtGui.QTableWidgetItem()
        self.DrugsTable.setHorizontalHeaderItem(23, item)
        item = QtGui.QTableWidgetItem()
        self.DrugsTable.setHorizontalHeaderItem(24, item)
        item = QtGui.QTableWidgetItem()
        self.DrugsTable.setHorizontalHeaderItem(25, item)
        item = QtGui.QTableWidgetItem()
        self.DrugsTable.setHorizontalHeaderItem(26, item)
        item = QtGui.QTableWidgetItem()
        self.DrugsTable.setHorizontalHeaderItem(27, item)
        item = QtGui.QTableWidgetItem()
        self.DrugsTable.setHorizontalHeaderItem(28, item)
        item = QtGui.QTableWidgetItem()
        self.DrugsTable.setHorizontalHeaderItem(29, item)
        item = QtGui.QTableWidgetItem()
        self.DrugsTable.setHorizontalHeaderItem(30, item)
        self.DrugsTable.horizontalHeader().setCascadingSectionResizes(False)
        self.DrugsTable.verticalHeader().setVisible(False)
        self.DrugsTable.verticalHeader().setCascadingSectionResizes(False)
        self.DrugsTable.verticalHeader().setDefaultSectionSize(30)
        self.DrugsTable.verticalHeader().setHighlightSections(True)
        self.Drug_Date = QtGui.QLabel(self.tab_2)
        self.Drug_Date.setGeometry(QtCore.QRect(1115, 790, 181, 16))
        self.Drug_Date.setStyleSheet(_fromUtf8("background:transparent;color:rgb(163, 8, 29);\n"
"color:white;font:bold;"))
        self.Drug_Date.setObjectName(_fromUtf8("Drug_Date"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1312, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuGfdgfd = QtGui.QMenu(self.menubar)
        self.menuGfdgfd.setObjectName(_fromUtf8("menuGfdgfd"))
        self.menuDf = QtGui.QMenu(self.menubar)
        self.menuDf.setObjectName(_fromUtf8("menuDf"))
        self.menuPoint_of_sale = QtGui.QMenu(self.menubar)
        self.menuPoint_of_sale.setObjectName(_fromUtf8("menuPoint_of_sale"))
        self.menuSetup = QtGui.QMenu(self.menubar)
        self.menuSetup.setObjectName(_fromUtf8("menuSetup"))
        self.menuUser_Management = QtGui.QMenu(self.menuSetup)
        self.menuUser_Management.setObjectName(_fromUtf8("menuUser_Management"))
        self.menuInventory = QtGui.QMenu(self.menubar)
        self.menuInventory.setObjectName(_fromUtf8("menuInventory"))
        self.menuSales_Invoice = QtGui.QMenu(self.menuInventory)
        self.menuSales_Invoice.setObjectName(_fromUtf8("menuSales_Invoice"))
        self.menuAccounting = QtGui.QMenu(self.menubar)
        self.menuAccounting.setObjectName(_fromUtf8("menuAccounting"))
        self.menuPayables = QtGui.QMenu(self.menuAccounting)
        self.menuPayables.setObjectName(_fromUtf8("menuPayables"))
        self.menuRecievals = QtGui.QMenu(self.menuAccounting)
        self.menuRecievals.setObjectName(_fromUtf8("menuRecievals"))
        self.menuReport = QtGui.QMenu(self.menubar)
        self.menuReport.setObjectName(_fromUtf8("menuReport"))
        self.menuSales_Report = QtGui.QMenu(self.menuReport)
        self.menuSales_Report.setObjectName(_fromUtf8("menuSales_Report"))
        self.menuInventory_Reports = QtGui.QMenu(self.menuReport)
        self.menuInventory_Reports.setObjectName(_fromUtf8("menuInventory_Reports"))
        self.menuStock_Movement = QtGui.QMenu(self.menuInventory_Reports)
        self.menuStock_Movement.setObjectName(_fromUtf8("menuStock_Movement"))
        self.menuGCT_Report = QtGui.QMenu(self.menuReport)
        self.menuGCT_Report.setObjectName(_fromUtf8("menuGCT_Report"))
        self.menuInsurance_Report = QtGui.QMenu(self.menuReport)
        self.menuInsurance_Report.setObjectName(_fromUtf8("menuInsurance_Report"))
        self.menuScript_Activity_Report = QtGui.QMenu(self.menuReport)
        self.menuScript_Activity_Report.setObjectName(_fromUtf8("menuScript_Activity_Report"))
        self.menuPayroll_reports = QtGui.QMenu(self.menuReport)
        self.menuPayroll_reports.setObjectName(_fromUtf8("menuPayroll_reports"))
        self.menuInternet = QtGui.QMenu(self.menubar)
        self.menuInternet.setObjectName(_fromUtf8("menuInternet"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSettings = QtGui.QAction(MainWindow)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionDispensary = QtGui.QAction(MainWindow)
        self.actionDispensary.setObjectName(_fromUtf8("actionDispensary"))
        self.actionCompany_information = QtGui.QAction(MainWindow)
        self.actionCompany_information.setObjectName(_fromUtf8("actionCompany_information"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionUser_Groups = QtGui.QAction(MainWindow)
        self.actionUser_Groups.setObjectName(_fromUtf8("actionUser_Groups"))
        self.actionUsers = QtGui.QAction(MainWindow)
        self.actionUsers.setObjectName(_fromUtf8("actionUsers"))
        self.actionDepartments = QtGui.QAction(MainWindow)
        self.actionDepartments.setObjectName(_fromUtf8("actionDepartments"))
        self.actionVendors = QtGui.QAction(MainWindow)
        self.actionVendors.setObjectName(_fromUtf8("actionVendors"))
        self.actionCustomers = QtGui.QAction(MainWindow)
        self.actionCustomers.setObjectName(_fromUtf8("actionCustomers"))
        self.actionFees_Service_Charges = QtGui.QAction(MainWindow)
        self.actionFees_Service_Charges.setObjectName(_fromUtf8("actionFees_Service_Charges"))
        self.actionLabel_codes = QtGui.QAction(MainWindow)
        self.actionLabel_codes.setObjectName(_fromUtf8("actionLabel_codes"))
        self.actionAuxillary_Labels = QtGui.QAction(MainWindow)
        self.actionAuxillary_Labels.setObjectName(_fromUtf8("actionAuxillary_Labels"))
        self.actionProduct_List = QtGui.QAction(MainWindow)
        self.actionProduct_List.setObjectName(_fromUtf8("actionProduct_List"))
        self.actionQuick_Order_Purchase_Order = QtGui.QAction(MainWindow)
        self.actionQuick_Order_Purchase_Order.setObjectName(_fromUtf8("actionQuick_Order_Purchase_Order"))
        self.actionInvoices_Stock_revieval = QtGui.QAction(MainWindow)
        self.actionInvoices_Stock_revieval.setObjectName(_fromUtf8("actionInvoices_Stock_revieval"))
        self.actionStock_Valuation = QtGui.QAction(MainWindow)
        self.actionStock_Valuation.setObjectName(_fromUtf8("actionStock_Valuation"))
        self.actionReturn_Order = QtGui.QAction(MainWindow)
        self.actionReturn_Order.setObjectName(_fromUtf8("actionReturn_Order"))
        self.actionCredit_Note_Recieved = QtGui.QAction(MainWindow)
        self.actionCredit_Note_Recieved.setObjectName(_fromUtf8("actionCredit_Note_Recieved"))
        self.actionCredit_Note_Issued = QtGui.QAction(MainWindow)
        self.actionCredit_Note_Issued.setObjectName(_fromUtf8("actionCredit_Note_Issued"))
        self.actionReset_Quantities_Zero_stock = QtGui.QAction(MainWindow)
        self.actionReset_Quantities_Zero_stock.setObjectName(_fromUtf8("actionReset_Quantities_Zero_stock"))
        self.actionSales_Invoices_by_Whole_Units = QtGui.QAction(MainWindow)
        self.actionSales_Invoices_by_Whole_Units.setObjectName(_fromUtf8("actionSales_Invoices_by_Whole_Units"))
        self.actionSales_Invoices_by_Units = QtGui.QAction(MainWindow)
        self.actionSales_Invoices_by_Units.setObjectName(_fromUtf8("actionSales_Invoices_by_Units"))
        self.actionLodgements = QtGui.QAction(MainWindow)
        self.actionLodgements.setObjectName(_fromUtf8("actionLodgements"))
        self.actionPayments_Issued = QtGui.QAction(MainWindow)
        self.actionPayments_Issued.setObjectName(_fromUtf8("actionPayments_Issued"))
        self.actionPayments_Recieved = QtGui.QAction(MainWindow)
        self.actionPayments_Recieved.setObjectName(_fromUtf8("actionPayments_Recieved"))
        self.actionInsurance_Reconcillation = QtGui.QAction(MainWindow)
        self.actionInsurance_Reconcillation.setObjectName(_fromUtf8("actionInsurance_Reconcillation"))
        self.actionProfit_Loss_Analysis = QtGui.QAction(MainWindow)
        self.actionProfit_Loss_Analysis.setObjectName(_fromUtf8("actionProfit_Loss_Analysis"))
        self.actionBalance_Sheet = QtGui.QAction(MainWindow)
        self.actionBalance_Sheet.setObjectName(_fromUtf8("actionBalance_Sheet"))
        self.actionBudget = QtGui.QAction(MainWindow)
        self.actionBudget.setObjectName(_fromUtf8("actionBudget"))
        self.actionInvoice_Summary = QtGui.QAction(MainWindow)
        self.actionInvoice_Summary.setObjectName(_fromUtf8("actionInvoice_Summary"))
        self.actionStatement = QtGui.QAction(MainWindow)
        self.actionStatement.setObjectName(_fromUtf8("actionStatement"))
        self.actionInvoice_Summary_2 = QtGui.QAction(MainWindow)
        self.actionInvoice_Summary_2.setObjectName(_fromUtf8("actionInvoice_Summary_2"))
        self.actionStatement_2 = QtGui.QAction(MainWindow)
        self.actionStatement_2.setObjectName(_fromUtf8("actionStatement_2"))
        self.actionPurchase_Reports = QtGui.QAction(MainWindow)
        self.actionPurchase_Reports.setObjectName(_fromUtf8("actionPurchase_Reports"))
        self.actionCashiers_Log = QtGui.QAction(MainWindow)
        self.actionCashiers_Log.setObjectName(_fromUtf8("actionCashiers_Log"))
        self.actionDaily_Sales = QtGui.QAction(MainWindow)
        self.actionDaily_Sales.setObjectName(_fromUtf8("actionDaily_Sales"))
        self.actionScript_Sales_Summary = QtGui.QAction(MainWindow)
        self.actionScript_Sales_Summary.setObjectName(_fromUtf8("actionScript_Sales_Summary"))
        self.actionDepartment_Sales = QtGui.QAction(MainWindow)
        self.actionDepartment_Sales.setObjectName(_fromUtf8("actionDepartment_Sales"))
        self.actionPurchase_Item_Details = QtGui.QAction(MainWindow)
        self.actionPurchase_Item_Details.setObjectName(_fromUtf8("actionPurchase_Item_Details"))
        self.actionCashiers_Sales_by_Item = QtGui.QAction(MainWindow)
        self.actionCashiers_Sales_by_Item.setObjectName(_fromUtf8("actionCashiers_Sales_by_Item"))
        self.actionExpiry_Report = QtGui.QAction(MainWindow)
        self.actionExpiry_Report.setObjectName(_fromUtf8("actionExpiry_Report"))
        self.actionTrends = QtGui.QAction(MainWindow)
        self.actionTrends.setObjectName(_fromUtf8("actionTrends"))
        self.actionExpired_Drugs = QtGui.QAction(MainWindow)
        self.actionExpired_Drugs.setObjectName(_fromUtf8("actionExpired_Drugs"))
        self.actionLow_Stock_Items = QtGui.QAction(MainWindow)
        self.actionLow_Stock_Items.setObjectName(_fromUtf8("actionLow_Stock_Items"))
        self.actionInactive_Items = QtGui.QAction(MainWindow)
        self.actionInactive_Items.setObjectName(_fromUtf8("actionInactive_Items"))
        self.actionBack_Ordered_Items = QtGui.QAction(MainWindow)
        self.actionBack_Ordered_Items.setObjectName(_fromUtf8("actionBack_Ordered_Items"))
        self.actionGraphs = QtGui.QAction(MainWindow)
        self.actionGraphs.setObjectName(_fromUtf8("actionGraphs"))
        self.actionInput_Tax = QtGui.QAction(MainWindow)
        self.actionInput_Tax.setObjectName(_fromUtf8("actionInput_Tax"))
        self.actionGCT_on_Prescriptions = QtGui.QAction(MainWindow)
        self.actionGCT_on_Prescriptions.setObjectName(_fromUtf8("actionGCT_on_Prescriptions"))
        self.actionGCT_on_Sales = QtGui.QAction(MainWindow)
        self.actionGCT_on_Sales.setObjectName(_fromUtf8("actionGCT_on_Sales"))
        self.actionClaims_Report = QtGui.QAction(MainWindow)
        self.actionClaims_Report.setObjectName(_fromUtf8("actionClaims_Report"))
        self.actionInsurance_Summary = QtGui.QAction(MainWindow)
        self.actionInsurance_Summary.setObjectName(_fromUtf8("actionInsurance_Summary"))
        self.actionClaims_Analysis = QtGui.QAction(MainWindow)
        self.actionClaims_Analysis.setObjectName(_fromUtf8("actionClaims_Analysis"))
        self.actionRx_Daily_Count = QtGui.QAction(MainWindow)
        self.actionRx_Daily_Count.setObjectName(_fromUtf8("actionRx_Daily_Count"))
        self.actionBy_Patient = QtGui.QAction(MainWindow)
        self.actionBy_Patient.setObjectName(_fromUtf8("actionBy_Patient"))
        self.actionBy_Doctor = QtGui.QAction(MainWindow)
        self.actionBy_Doctor.setObjectName(_fromUtf8("actionBy_Doctor"))
        self.actionBy_User = QtGui.QAction(MainWindow)
        self.actionBy_User.setObjectName(_fromUtf8("actionBy_User"))
        self.actionPrescription_Fee_Totals = QtGui.QAction(MainWindow)
        self.actionPrescription_Fee_Totals.setObjectName(_fromUtf8("actionPrescription_Fee_Totals"))
        self.actionPrescription_Day_Book = QtGui.QAction(MainWindow)
        self.actionPrescription_Day_Book.setObjectName(_fromUtf8("actionPrescription_Day_Book"))
        self.actionPayslips = QtGui.QAction(MainWindow)
        self.actionPayslips.setObjectName(_fromUtf8("actionPayslips"))
        self.actionTime_Log = QtGui.QAction(MainWindow)
        self.actionTime_Log.setObjectName(_fromUtf8("actionTime_Log"))
        self.actionBudget_Report = QtGui.QAction(MainWindow)
        self.actionBudget_Report.setObjectName(_fromUtf8("actionBudget_Report"))
        self.SettingsMenu = QtGui.QAction(MainWindow)
        self.SettingsMenu.setObjectName(_fromUtf8("SettingsMenu"))
        self.actionTax = QtGui.QAction(MainWindow)
        self.actionTax.setObjectName(_fromUtf8("actionTax"))
        self.actionDoctors = QtGui.QAction(MainWindow)
        self.actionDoctors.setObjectName(_fromUtf8("actionDoctors"))
        self.actionRx_No = QtGui.QAction(MainWindow)
        self.actionRx_No.setObjectName(_fromUtf8("actionRx_No"))
        self.menuGfdgfd.addAction(self.SettingsMenu)
        self.menuGfdgfd.addAction(self.actionRx_No)
        self.menuUser_Management.addAction(self.actionUser_Groups)
        self.menuUser_Management.addAction(self.actionUsers)
        self.menuSetup.addAction(self.actionCompany_information)
        self.menuSetup.addAction(self.actionPreferences)
        self.menuSetup.addAction(self.menuUser_Management.menuAction())
        self.menuSetup.addAction(self.actionDepartments)
        self.menuSetup.addAction(self.actionVendors)
        self.menuSetup.addAction(self.actionCustomers)
        self.menuSetup.addAction(self.actionFees_Service_Charges)
        self.menuSetup.addAction(self.actionLabel_codes)
        self.menuSetup.addAction(self.actionAuxillary_Labels)
        self.menuSetup.addAction(self.actionTax)
        self.menuSetup.addAction(self.actionDoctors)
        self.menuSales_Invoice.addAction(self.actionSales_Invoices_by_Whole_Units)
        self.menuSales_Invoice.addAction(self.actionSales_Invoices_by_Units)
        self.menuInventory.addAction(self.actionProduct_List)
        self.menuInventory.addAction(self.actionQuick_Order_Purchase_Order)
        self.menuInventory.addAction(self.actionInvoices_Stock_revieval)
        self.menuInventory.addAction(self.actionStock_Valuation)
        self.menuInventory.addAction(self.actionReturn_Order)
        self.menuInventory.addAction(self.actionCredit_Note_Recieved)
        self.menuInventory.addAction(self.actionCredit_Note_Issued)
        self.menuInventory.addAction(self.menuSales_Invoice.menuAction())
        self.menuInventory.addAction(self.actionReset_Quantities_Zero_stock)
        self.menuPayables.addAction(self.actionInvoice_Summary)
        self.menuPayables.addAction(self.actionStatement)
        self.menuRecievals.addAction(self.actionInvoice_Summary_2)
        self.menuRecievals.addAction(self.actionStatement_2)
        self.menuAccounting.addAction(self.actionLodgements)
        self.menuAccounting.addAction(self.actionPayments_Issued)
        self.menuAccounting.addAction(self.actionPayments_Recieved)
        self.menuAccounting.addAction(self.actionInsurance_Reconcillation)
        self.menuAccounting.addAction(self.actionProfit_Loss_Analysis)
        self.menuAccounting.addAction(self.actionBalance_Sheet)
        self.menuAccounting.addAction(self.actionBudget)
        self.menuAccounting.addAction(self.menuRecievals.menuAction())
        self.menuAccounting.addAction(self.menuPayables.menuAction())
        self.menuSales_Report.addAction(self.actionCashiers_Log)
        self.menuSales_Report.addAction(self.actionDaily_Sales)
        self.menuSales_Report.addAction(self.actionScript_Sales_Summary)
        self.menuSales_Report.addAction(self.actionDepartment_Sales)
        self.menuStock_Movement.addAction(self.actionExpired_Drugs)
        self.menuStock_Movement.addAction(self.actionLow_Stock_Items)
        self.menuStock_Movement.addAction(self.actionInactive_Items)
        self.menuStock_Movement.addAction(self.actionBack_Ordered_Items)
        self.menuInventory_Reports.addAction(self.actionPurchase_Item_Details)
        self.menuInventory_Reports.addAction(self.actionCashiers_Sales_by_Item)
        self.menuInventory_Reports.addAction(self.actionExpiry_Report)
        self.menuInventory_Reports.addAction(self.actionTrends)
        self.menuInventory_Reports.addAction(self.menuStock_Movement.menuAction())
        self.menuGCT_Report.addAction(self.actionInput_Tax)
        self.menuGCT_Report.addAction(self.actionGCT_on_Prescriptions)
        self.menuGCT_Report.addAction(self.actionGCT_on_Sales)
        self.menuInsurance_Report.addAction(self.actionClaims_Report)
        self.menuInsurance_Report.addAction(self.actionInsurance_Summary)
        self.menuInsurance_Report.addAction(self.actionClaims_Analysis)
        self.menuScript_Activity_Report.addAction(self.actionRx_Daily_Count)
        self.menuScript_Activity_Report.addAction(self.actionBy_Patient)
        self.menuScript_Activity_Report.addAction(self.actionBy_Doctor)
        self.menuScript_Activity_Report.addAction(self.actionBy_User)
        self.menuScript_Activity_Report.addAction(self.actionPrescription_Fee_Totals)
        self.menuScript_Activity_Report.addAction(self.actionPrescription_Day_Book)
        self.menuPayroll_reports.addAction(self.actionPayslips)
        self.menuPayroll_reports.addAction(self.actionTime_Log)
        self.menuReport.addAction(self.actionPurchase_Reports)
        self.menuReport.addAction(self.menuSales_Report.menuAction())
        self.menuReport.addAction(self.menuInventory_Reports.menuAction())
        self.menuReport.addAction(self.actionGraphs)
        self.menuReport.addAction(self.menuGCT_Report.menuAction())
        self.menuReport.addAction(self.menuInsurance_Report.menuAction())
        self.menuReport.addAction(self.menuScript_Activity_Report.menuAction())
        self.menuReport.addAction(self.menuPayroll_reports.menuAction())
        self.menuReport.addAction(self.actionBudget_Report)
        self.menubar.addAction(self.menuGfdgfd.menuAction())
        self.menubar.addAction(self.menuDf.menuAction())
        self.menubar.addAction(self.menuPoint_of_sale.menuAction())
        self.menubar.addAction(self.menuSetup.menuAction())
        self.menubar.addAction(self.menuInventory.menuAction())
        self.menubar.addAction(self.menuAccounting.menuAction())
        self.menubar.addAction(self.menuReport.menuAction())
        self.menubar.addAction(self.menuInternet.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.BPrint.setText(_translate("MainWindow", "F6-Print", None))
        self.BNext.setText(_translate("MainWindow", "F8-Next =>", None))
        self.BLookup.setText(_translate("MainWindow", "F5-View Rx", None))
        self.BCalculator.setText(_translate("MainWindow", "Calculator", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Preview", None))
        self.label_4.setText(_translate("MainWindow", "Total", None))
        self.label_5.setText(_translate("MainWindow", "NHF", None))
        self.label_6.setText(_translate("MainWindow", "INS 1", None))
        self.label_7.setText(_translate("MainWindow", "INS 2 & 3", None))
        self.label_8.setText(_translate("MainWindow", "Co-pay", None))
        self.label_9.setText(_translate("MainWindow", "Agreed discount", None))
        self.label_10.setText(_translate("MainWindow", "Discount", None))
        self.RTotal.setText(_translate("MainWindow", "$0.00", None))
        self.RNhf.setText(_translate("MainWindow", "0", None))
        self.RDrug.setText(_translate("MainWindow", "$0.00", None))
        self.R31.setText(_translate("MainWindow", "$0.00", None))
        self.R32.setText(_translate("MainWindow", "$0.00", None))
        self.RCo.setText(_translate("MainWindow", "$0.00", None))
        self.RAgreed.setText(_translate("MainWindow", "$0.00", None))
        self.RDiscount.setItemText(0, _translate("MainWindow", "0", None))
        self.label_11.setText(_translate("MainWindow", "$0.00", None))
        self.label_12.setText(_translate("MainWindow", "NHF Pays: $ 0.00, Patient Pays $ 0.00", None))
        self.ApplyMain.setText(_translate("MainWindow", "Apply", None))
        self.BQuote.setText(_translate("MainWindow", "F7-Quote", None))
        self.BInternet.setText(_translate("MainWindow", "Internet", None))
        self.groupBox.setTitle(_translate("MainWindow", "Patient", None))
        self.label.setText(_translate("MainWindow", "Name", None))
        self.label_2.setText(_translate("MainWindow", "Doctor", None))
        self.label_3.setText(_translate("MainWindow", "Source", None))
        self.PSource.setItemText(0, _translate("MainWindow", "Private", None))
        self.PSource.setItemText(1, _translate("MainWindow", "Public", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Rx", None))
        self.label_13.setText(_translate("MainWindow", "Rx No", None))
        self.NewScript.setText(_translate("MainWindow", "New Script", None))
        self.label_14.setText(_translate("MainWindow", "The Automated Pharmacy", None))
        self.MyDate.setText(_translate("MainWindow", "Tue Jun  5 02:57:12 2018", None))
        self.BClose.setText(_translate("MainWindow", "Close", None))
        item = self.MainTableX.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "DRUG", None))
        item = self.MainTableX.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "QTY", None))
        item = self.MainTableX.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "COST", None))
        item = self.MainTableX.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "INS", None))
        item = self.MainTableX.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "FEES", None))
        item = self.MainTableX.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "LABEL", None))
        item = self.MainTableX.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "DAYS", None))
        item = self.MainTableX.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "REFILLS", None))
        item = self.MainTableX.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "EXTENDED", None))
        item = self.MainTableX.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "TAX", None))
        item = self.MainTableX.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "NHF", None))
        item = self.MainTableX.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "VOID", None))
        item = self.MainTableX.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "DISCOUNT", None))
        item = self.MainTableX.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "PRINTED", None))
        item = self.MainTableX.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "OS", None))
        item = self.MainTableX.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "IND", None))
        item = self.MainTableX.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "DIAGC", None))
        self.BLabel.setText(_translate("MainWindow", "F3-Label", None))
        self.BDrugs.setText(_translate("MainWindow", "F2-Drugs", None))
        self.BPatient.setText(_translate("MainWindow", "F4-Patient", None))
        self.BReversal.setText(_translate("MainWindow", "Reversal", None))
        self.BDelete.setText(_translate("MainWindow", "CTRL-F9-Delete Rx", None))
        self.AddPresc.setText(_translate("MainWindow", "Add", None))
        self.DeletePresc.setText(_translate("MainWindow", "Delete", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Dispensary_tab), _translate("MainWindow", "Dispensary", None))
        item = self.SHTable1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "RECEIPT", None))
        item = self.SHTable1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "SALEDATE", None))
        item = self.SHTable1.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "SALETIME", None))
        item = self.SHTable1.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "SUBTOTAL", None))
        item = self.SHTable1.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "TAX", None))
        item = self.SHTable1.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "DISCOUNT", None))
        item = self.SHTable1.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "SALETYPE", None))
        item = self.SHTable1.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "USR", None))
        item = self.SHTable1.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "EXEMPTED", None))
        item = self.SHTable1.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "PAYMENT", None))
        item = self.SHTable1.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "PAYMODE", None))
        item = self.SHTable1.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "NAME", None))
        item = self.SHTable1.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Address", None))
        item = self.SHTable1.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "CHARGEAc", None))
        item = self.SHTable1.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "CARDNUMBER", None))
        item = self.SHTable1.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "INVOICE", None))
        item = self.SHTable1.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "RXND", None))
        item = self.SHTable1.horizontalHeaderItem(17)
        item.setText(_translate("MainWindow", "BALANCE", None))
        item = self.SHTable1.horizontalHeaderItem(18)
        item.setText(_translate("MainWindow", "2 nd PAYMENT", None))
        item = self.SHTable1.horizontalHeaderItem(19)
        item.setText(_translate("MainWindow", "PAYMODE2", None))
        item = self.SHTable2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "DESCRIPTION", None))
        item = self.SHTable2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "QUANTITY", None))
        item = self.SHTable2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "PRICE", None))
        item = self.SHTable2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "DISCOUNT", None))
        item = self.SHTable2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "TAX", None))
        item = self.SHTable2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Receipt", None))
        item = self.SHTable2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "STATUS", None))
        self.SHPrint.setText(_translate("MainWindow", "Print", None))
        self.label_15.setText(_translate("MainWindow", "Sales history", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Range", None))
        self.label_16.setText(_translate("MainWindow", "To", None))
        self.SHRefresh.setText(_translate("MainWindow", "Refresh", None))
        self.SHClose.setText(_translate("MainWindow", "Close", None))
        self.SMy_Date.setText(_translate("MainWindow", "Tue Jun  5 02:57:12 2018", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Sales_Tab), _translate("MainWindow", "Sales History", None))
        self.label_17.setText(_translate("MainWindow", "PURCHASE HISTORY", None))
        self.PHClose.setText(_translate("MainWindow", "Close", None))
        self.label_18.setText(_translate("MainWindow", "Product", None))
        self.PHPrint.setText(_translate("MainWindow", "Print", None))
        item = self.PHTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "SUPPLIER", None))
        item = self.PHTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "PACKAGE", None))
        item = self.PHTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "NUMBER", None))
        item = self.PHTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "DATE", None))
        item = self.PHTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "QUANTITY", None))
        item = self.PHTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "COST", None))
        item = self.PHTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "GCT", None))
        item = self.PHTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "TAXED", None))
        item = self.PHTable.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "LOTNO", None))
        item = self.PHTable.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "EXPIRY", None))
        item = self.PHTable.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "DISCOUNT", None))
        item = self.PHTable.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "ITEM", None))
        item = self.PHTable.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Prv Qty", None))
        self.PHTotals.setText(_translate("MainWindow", "Totals : ", None))
        self.PHQty.setText(_translate("MainWindow", "Qty : ", None))
        self.PHValue.setText(_translate("MainWindow", "Value : ", None))
        self.PMy_Date.setText(_translate("MainWindow", "Tue Jun  5 02:57:12 2018", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Purchase History", None))
        self.label_19.setText(_translate("MainWindow", "Lookup", None))
        self.SearchDrugs.setText(_translate("MainWindow", "Search", None))
        self.EditDrugs.setText(_translate("MainWindow", "Edit", None))
        self.RefreshDrugs.setText(_translate("MainWindow", "Refresh", None))
        self.CloseDrugs.setText(_translate("MainWindow", "Close", None))
        self.NewDrugs.setText(_translate("MainWindow", "New", None))
        self.DeleteDrugs.setText(_translate("MainWindow", "Delete", None))
        self.SelectDrug.setText(_translate("MainWindow", "Select", None))
        self.SearchByWhat.setItemText(0, _translate("MainWindow", "DESCRIPTION", None))
        self.SearchByWhat.setItemText(1, _translate("MainWindow", "NUM", None))
        self.SearchByWhat.setItemText(2, _translate("MainWindow", "BARCODE", None))
        item = self.DrugsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID", None))
        item = self.DrugsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "DESCRIPTION", None))
        item = self.DrugsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "GENERIC NAME", None))
        item = self.DrugsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "NUMBER", None))
        item = self.DrugsTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "TYPE", None))
        item = self.DrugsTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "CATEGORY", None))
        item = self.DrugsTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "PACKSIZE", None))
        item = self.DrugsTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "QOH", None))
        item = self.DrugsTable.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "PRICE", None))
        item = self.DrugsTable.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "TAXCODE", None))
        item = self.DrugsTable.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "PRODCODE", None))
        item = self.DrugsTable.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "SUP_NAME", None))
        item = self.DrugsTable.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "BARCODE", None))
        item = self.DrugsTable.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "TOTAL QTY", None))
        item = self.DrugsTable.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "MISC", None))
        item = self.DrugsTable.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "ALTERNATE SUPPLIER", None))
        item = self.DrugsTable.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "LOOSE QTY", None))
        item = self.DrugsTable.horizontalHeaderItem(17)
        item.setText(_translate("MainWindow", "UNIT OF MEASURE", None))
        item = self.DrugsTable.horizontalHeaderItem(18)
        item.setText(_translate("MainWindow", "MAX QTY", None))
        item = self.DrugsTable.horizontalHeaderItem(19)
        item.setText(_translate("MainWindow", "REORDER LVL", None))
        item = self.DrugsTable.horizontalHeaderItem(20)
        item.setText(_translate("MainWindow", "REORDER QTY", None))
        item = self.DrugsTable.horizontalHeaderItem(21)
        item.setText(_translate("MainWindow", "BACKORDER", None))
        item = self.DrugsTable.horizontalHeaderItem(22)
        item.setText(_translate("MainWindow", "MARKUP", None))
        item = self.DrugsTable.horizontalHeaderItem(23)
        item.setText(_translate("MainWindow", "EACH PRICE", None))
        item = self.DrugsTable.horizontalHeaderItem(24)
        item.setText(_translate("MainWindow", "WHOLE PRICE", None))
        item = self.DrugsTable.horizontalHeaderItem(25)
        item.setText(_translate("MainWindow", "AVG COST", None))
        item = self.DrugsTable.horizontalHeaderItem(26)
        item.setText(_translate("MainWindow", "LAST COST", None))
        item = self.DrugsTable.horizontalHeaderItem(27)
        item.setText(_translate("MainWindow", "PRICE BREAK AT", None))
        item = self.DrugsTable.horizontalHeaderItem(28)
        item.setText(_translate("MainWindow", "BREAK PRICE", None))
        item = self.DrugsTable.horizontalHeaderItem(29)
        item.setText(_translate("MainWindow", "NHF BENEFIT", None))
        item = self.DrugsTable.horizontalHeaderItem(30)
        item.setText(_translate("MainWindow", "PRESCRIPTION", None))
        self.Drug_Date.setText(_translate("MainWindow", "Tue Jun  5 02:57:12 2018", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Inventory", None))
        self.menuGfdgfd.setTitle(_translate("MainWindow", "Settings", None))
        self.menuDf.setTitle(_translate("MainWindow", "Dispensary", None))
        self.menuPoint_of_sale.setTitle(_translate("MainWindow", "Point of sale", None))
        self.menuSetup.setTitle(_translate("MainWindow", "Setup", None))
        self.menuUser_Management.setTitle(_translate("MainWindow", "User Management", None))
        self.menuInventory.setTitle(_translate("MainWindow", "Inventory", None))
        self.menuSales_Invoice.setTitle(_translate("MainWindow", "Sales Invoice", None))
        self.menuAccounting.setTitle(_translate("MainWindow", "Accounting", None))
        self.menuPayables.setTitle(_translate("MainWindow", "Payables", None))
        self.menuRecievals.setTitle(_translate("MainWindow", "Recievals", None))
        self.menuReport.setTitle(_translate("MainWindow", "Reports", None))
        self.menuSales_Report.setTitle(_translate("MainWindow", "Sales Report", None))
        self.menuInventory_Reports.setTitle(_translate("MainWindow", "Inventory Reports", None))
        self.menuStock_Movement.setTitle(_translate("MainWindow", "Stock Movement", None))
        self.menuGCT_Report.setTitle(_translate("MainWindow", "GCT Report", None))
        self.menuInsurance_Report.setTitle(_translate("MainWindow", "Insurance Report", None))
        self.menuScript_Activity_Report.setTitle(_translate("MainWindow", "Script Activity Report", None))
        self.menuPayroll_reports.setTitle(_translate("MainWindow", "Payroll reports", None))
        self.menuInternet.setTitle(_translate("MainWindow", "Internet", None))
        self.menuTools.setTitle(_translate("MainWindow", "Tools", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionSettings.setText(_translate("MainWindow", "Settings", None))
        self.actionDispensary.setText(_translate("MainWindow", "Dispensary", None))
        self.actionCompany_information.setText(_translate("MainWindow", "Company information", None))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences", None))
        self.actionUser_Groups.setText(_translate("MainWindow", "User Groups", None))
        self.actionUsers.setText(_translate("MainWindow", "Users", None))
        self.actionDepartments.setText(_translate("MainWindow", "Departments", None))
        self.actionVendors.setText(_translate("MainWindow", "Vendors", None))
        self.actionCustomers.setText(_translate("MainWindow", "Customers", None))
        self.actionFees_Service_Charges.setText(_translate("MainWindow", "Fees & Service Charges", None))
        self.actionLabel_codes.setText(_translate("MainWindow", "Label codes", None))
        self.actionAuxillary_Labels.setText(_translate("MainWindow", "Auxillary Labels", None))
        self.actionProduct_List.setText(_translate("MainWindow", "Product List", None))
        self.actionQuick_Order_Purchase_Order.setText(_translate("MainWindow", "Quick Order / Purchase Order", None))
        self.actionInvoices_Stock_revieval.setText(_translate("MainWindow", "Invoices ( Stock revieval )", None))
        self.actionStock_Valuation.setText(_translate("MainWindow", "Stock Valuation", None))
        self.actionReturn_Order.setText(_translate("MainWindow", "Return Order", None))
        self.actionCredit_Note_Recieved.setText(_translate("MainWindow", "Credit Note Recieved", None))
        self.actionCredit_Note_Issued.setText(_translate("MainWindow", "Credit Note Issued", None))
        self.actionReset_Quantities_Zero_stock.setText(_translate("MainWindow", "Reset Quantities ( Zero stock ) ", None))
        self.actionSales_Invoices_by_Whole_Units.setText(_translate("MainWindow", "Sales Invoices by Whole Units", None))
        self.actionSales_Invoices_by_Units.setText(_translate("MainWindow", "Sales Invoices by Units", None))
        self.actionLodgements.setText(_translate("MainWindow", "Lodgements", None))
        self.actionPayments_Issued.setText(_translate("MainWindow", "Payments Issued", None))
        self.actionPayments_Recieved.setText(_translate("MainWindow", "Payments Recieved", None))
        self.actionInsurance_Reconcillation.setText(_translate("MainWindow", "Insurance Reconcillation", None))
        self.actionProfit_Loss_Analysis.setText(_translate("MainWindow", "Profit & Loss Analysis", None))
        self.actionBalance_Sheet.setText(_translate("MainWindow", "Balance Sheet", None))
        self.actionBudget.setText(_translate("MainWindow", "Budget", None))
        self.actionInvoice_Summary.setText(_translate("MainWindow", "Invoice Summary", None))
        self.actionStatement.setText(_translate("MainWindow", "Statement", None))
        self.actionInvoice_Summary_2.setText(_translate("MainWindow", "Invoice Summary", None))
        self.actionStatement_2.setText(_translate("MainWindow", "Statement", None))
        self.actionPurchase_Reports.setText(_translate("MainWindow", "Purchase Reports", None))
        self.actionCashiers_Log.setText(_translate("MainWindow", "Cashiers Log", None))
        self.actionDaily_Sales.setText(_translate("MainWindow", "Daily Sales", None))
        self.actionScript_Sales_Summary.setText(_translate("MainWindow", "Script Sales Summary", None))
        self.actionDepartment_Sales.setText(_translate("MainWindow", "Department Sales", None))
        self.actionPurchase_Item_Details.setText(_translate("MainWindow", "Purchase Item Details", None))
        self.actionCashiers_Sales_by_Item.setText(_translate("MainWindow", "Cashiers Sales by Item", None))
        self.actionExpiry_Report.setText(_translate("MainWindow", "Expiry Report", None))
        self.actionTrends.setText(_translate("MainWindow", "Trends", None))
        self.actionExpired_Drugs.setText(_translate("MainWindow", "Expired Drugs", None))
        self.actionLow_Stock_Items.setText(_translate("MainWindow", "Low Stock Items", None))
        self.actionInactive_Items.setText(_translate("MainWindow", "Inactive Items", None))
        self.actionBack_Ordered_Items.setText(_translate("MainWindow", "Back Ordered Items", None))
        self.actionGraphs.setText(_translate("MainWindow", "Graphs", None))
        self.actionInput_Tax.setText(_translate("MainWindow", "Input Tax", None))
        self.actionGCT_on_Prescriptions.setText(_translate("MainWindow", "GCT on Prescriptions", None))
        self.actionGCT_on_Sales.setText(_translate("MainWindow", "GCT on Sales", None))
        self.actionClaims_Report.setText(_translate("MainWindow", "Claims Report", None))
        self.actionInsurance_Summary.setText(_translate("MainWindow", "Insurance Summary", None))
        self.actionClaims_Analysis.setText(_translate("MainWindow", "Claims Analysis", None))
        self.actionRx_Daily_Count.setText(_translate("MainWindow", "Rx Daily Count", None))
        self.actionBy_Patient.setText(_translate("MainWindow", "By Patient", None))
        self.actionBy_Doctor.setText(_translate("MainWindow", "By Doctor", None))
        self.actionBy_User.setText(_translate("MainWindow", "By User", None))
        self.actionPrescription_Fee_Totals.setText(_translate("MainWindow", "Prescription Fee Totals", None))
        self.actionPrescription_Day_Book.setText(_translate("MainWindow", "Prescription Day Book", None))
        self.actionPayslips.setText(_translate("MainWindow", "Payslips", None))
        self.actionTime_Log.setText(_translate("MainWindow", "Time Log", None))
        self.actionBudget_Report.setText(_translate("MainWindow", "Budget Report", None))
        self.SettingsMenu.setText(_translate("MainWindow", "Products categories", None))
        self.actionTax.setText(_translate("MainWindow", "Tax", None))
        self.actionDoctors.setText(_translate("MainWindow", "Doctors", None))
        self.actionRx_No.setText(_translate("MainWindow", "Rx No", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

