# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\achill123\Desktop\PharmaProject\InsertPatient.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_IInsertPatient_2(object):
    def setupUi(self, IInsertPatient_2):
        IInsertPatient_2.setObjectName(_fromUtf8("IInsertPatient_2"))
        IInsertPatient_2.resize(495, 426)
        IInsertPatient_2.setMinimumSize(QtCore.QSize(495, 426))
        IInsertPatient_2.setMaximumSize(QtCore.QSize(495, 426))
        IInsertPatient_2.setStyleSheet(_fromUtf8("color:white;"))
        self.InsertPatient = QtGui.QTabWidget(IInsertPatient_2)
        self.InsertPatient.setGeometry(QtCore.QRect(0, 0, 501, 771))
        self.InsertPatient.setStyleSheet(_fromUtf8(""))
        self.InsertPatient.setObjectName(_fromUtf8("InsertPatient"))
        self.tabWidgetPage1 = QtGui.QWidget()
        self.tabWidgetPage1.setObjectName(_fromUtf8("tabWidgetPage1"))
        self.label = QtGui.QLabel(self.tabWidgetPage1)
        self.label.setGeometry(QtCore.QRect(30, 30, 53, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 53, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_3.setGeometry(QtCore.QRect(30, 100, 53, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_4.setGeometry(QtCore.QRect(30, 130, 53, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_5.setGeometry(QtCore.QRect(20, 170, 71, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_6.setGeometry(QtCore.QRect(30, 200, 53, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_7.setGeometry(QtCore.QRect(30, 230, 53, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_8.setGeometry(QtCore.QRect(40, 280, 53, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_9.setGeometry(QtCore.QRect(40, 320, 53, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_10.setGeometry(QtCore.QRect(40, 360, 71, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_11.setGeometry(QtCore.QRect(40, 400, 53, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_12.setGeometry(QtCore.QRect(40, 436, 53, 20))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_13.setGeometry(QtCore.QRect(50, 520, 53, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_14.setGeometry(QtCore.QRect(50, 550, 53, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_15.setGeometry(QtCore.QRect(50, 600, 53, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_16.setGeometry(QtCore.QRect(22, 640, 81, 20))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.IInsertPatient = QtGui.QStackedWidget(self.tabWidgetPage1)
        self.IInsertPatient.setGeometry(QtCore.QRect(-10, -20, 511, 841))
        self.IInsertPatient.setStyleSheet(_fromUtf8("background-color:rgb(75, 226, 226);\n"
"color: rgb(177, 33, 23);\n"
"font: 75 bold 8pt \"Yu Gothic UI Semibold\";"))
        self.IInsertPatient.setObjectName(_fromUtf8("IInsertPatient"))
        self.stackedWidget_2Page1 = QtGui.QWidget()
        self.stackedWidget_2Page1.setObjectName(_fromUtf8("stackedWidget_2Page1"))
        self.label_17 = QtGui.QLabel(self.stackedWidget_2Page1)
        self.label_17.setGeometry(QtCore.QRect(21, 31, 36, 17))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.stackedWidget_2Page1)
        self.label_18.setGeometry(QtCore.QRect(21, 71, 44, 17))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(self.stackedWidget_2Page1)
        self.label_19.setGeometry(QtCore.QRect(21, 111, 39, 17))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.stackedWidget_2Page1)
        self.label_20.setGeometry(QtCore.QRect(21, 150, 25, 17))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.stackedWidget_2Page1)
        self.label_21.setGeometry(QtCore.QRect(21, 190, 59, 17))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.stackedWidget_2Page1)
        self.label_22.setGeometry(QtCore.QRect(21, 230, 49, 17))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_25 = QtGui.QLabel(self.stackedWidget_2Page1)
        self.label_25.setGeometry(QtCore.QRect(21, 269, 46, 17))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_28 = QtGui.QLabel(self.stackedWidget_2Page1)
        self.label_28.setGeometry(QtCore.QRect(21, 308, 49, 17))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_29 = QtGui.QLabel(self.stackedWidget_2Page1)
        self.label_29.setGeometry(QtCore.QRect(21, 348, 26, 17))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.IName = QtGui.QLineEdit(self.stackedWidget_2Page1)
        self.IName.setGeometry(QtCore.QRect(90, 30, 154, 23))
        self.IName.setStyleSheet(_fromUtf8("background-color:white"))
        self.IName.setObjectName(_fromUtf8("IName"))
        self.IPhone1 = QtGui.QLineEdit(self.stackedWidget_2Page1)
        self.IPhone1.setGeometry(QtCore.QRect(90, 110, 154, 23))
        self.IPhone1.setStyleSheet(_fromUtf8("background-color:white\n"
""))
        self.IPhone1.setObjectName(_fromUtf8("IPhone1"))
        self.ITrn = QtGui.QLineEdit(self.stackedWidget_2Page1)
        self.ITrn.setGeometry(QtCore.QRect(90, 150, 154, 23))
        self.ITrn.setStyleSheet(_fromUtf8("background-color:white\n"
""))
        self.ITrn.setObjectName(_fromUtf8("ITrn"))
        self.INhf = QtGui.QLineEdit(self.stackedWidget_2Page1)
        self.INhf.setGeometry(QtCore.QRect(90, 230, 154, 23))
        self.INhf.setStyleSheet(_fromUtf8("background-color:white\n"
""))
        self.INhf.setObjectName(_fromUtf8("INhf"))
        self.IBalance = QtGui.QLineEdit(self.stackedWidget_2Page1)
        self.IBalance.setGeometry(QtCore.QRect(90, 270, 154, 23))
        self.IBalance.setStyleSheet(_fromUtf8("background-color:white\n"
""))
        self.IBalance.setObjectName(_fromUtf8("IBalance"))
        self.IAddress = QtGui.QLineEdit(self.stackedWidget_2Page1)
        self.IAddress.setGeometry(QtCore.QRect(90, 310, 154, 23))
        self.IAddress.setStyleSheet(_fromUtf8("background-color:white\n"
""))
        self.IAddress.setObjectName(_fromUtf8("IAddress"))
        self.IGender = QtGui.QComboBox(self.stackedWidget_2Page1)
        self.IGender.setGeometry(QtCore.QRect(90, 70, 151, 23))
        self.IGender.setStyleSheet(_fromUtf8("background-color:rgb(240,240,240);"))
        self.IGender.setObjectName(_fromUtf8("IGender"))
        self.IGender.addItem(_fromUtf8(""))
        self.IGender.addItem(_fromUtf8(""))
        self.IInsurance = QtGui.QComboBox(self.stackedWidget_2Page1)
        self.IInsurance.setGeometry(QtCore.QRect(90, 190, 151, 23))
        self.IInsurance.setObjectName(_fromUtf8("IInsurance"))
        self.IInsurance.addItem(_fromUtf8(""))
        self.label_33 = QtGui.QLabel(self.stackedWidget_2Page1)
        self.label_33.setGeometry(QtCore.QRect(380, 20, 91, 71))
        self.label_33.setStyleSheet(_fromUtf8("font: 87 italic 10pt \"Arial Black\";"))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.IFlag = QtGui.QCheckBox(self.stackedWidget_2Page1)
        self.IFlag.setGeometry(QtCore.QRect(350, 150, 91, 20))
        self.IFlag.setStyleSheet(_fromUtf8("color:red;\n"
"font: 75 8pt \"Lucida Sans Unicode\";"))
        self.IFlag.setObjectName(_fromUtf8("IFlag"))
        self.IDob = QtGui.QDateEdit(self.stackedWidget_2Page1)
        self.IDob.setGeometry(QtCore.QRect(90, 350, 110, 22))
        self.IDob.setStyleSheet(_fromUtf8("background-color:white"))
        self.IDob.setObjectName(_fromUtf8("IDob"))
        self.IOk = QtGui.QPushButton(self.stackedWidget_2Page1)
        self.IOk.setGeometry(QtCore.QRect(360, 350, 93, 31))
        self.IOk.setStyleSheet(_fromUtf8("color:white;font:bold;\n"
"\n"
"background:qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(32, 221, 225, 179), stop:0.497326 rgba(0, 0, 0, 147), stop:1 rgba(0, 169, 255, 147));"))
        self.IOk.setObjectName(_fromUtf8("IOk"))
        self.IPhone2 = QtGui.QLineEdit(self.stackedWidget_2Page1)
        self.IPhone2.setGeometry(QtCore.QRect(250, 110, 154, 23))
        self.IPhone2.setStyleSheet(_fromUtf8("background-color:white\n"
""))
        self.IPhone2.setObjectName(_fromUtf8("IPhone2"))
        self.IInsertPatient.addWidget(self.stackedWidget_2Page1)
        self.stackedWidget_2Page2 = QtGui.QWidget()
        self.stackedWidget_2Page2.setObjectName(_fromUtf8("stackedWidget_2Page2"))
        self.IInsertPatient.addWidget(self.stackedWidget_2Page2)
        self.InsertPatient.addTab(self.tabWidgetPage1, _fromUtf8(""))

        self.retranslateUi(IInsertPatient_2)
        self.InsertPatient.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(IInsertPatient_2)

    def retranslateUi(self, IInsertPatient_2):
        IInsertPatient_2.setWindowTitle(_translate("IInsertPatient_2", "Dialog", None))
        self.InsertPatient.setWhatsThis(_translate("IInsertPatient_2", "<html><head/><body><p>Insert patient</p><p><br/></p></body></html>", None))
        self.label.setText(_translate("IInsertPatient_2", "Name", None))
        self.label_2.setText(_translate("IInsertPatient_2", "Gender", None))
        self.label_3.setText(_translate("IInsertPatient_2", "Phone", None))
        self.label_4.setText(_translate("IInsertPatient_2", "TRN", None))
        self.label_5.setText(_translate("IInsertPatient_2", "Insurance", None))
        self.label_6.setText(_translate("IInsertPatient_2", "NHF No", None))
        self.label_7.setText(_translate("IInsertPatient_2", "Policy No", None))
        self.label_8.setText(_translate("IInsertPatient_2", "JADEP", None))
        self.label_9.setText(_translate("IInsertPatient_2", "Balance", None))
        self.label_10.setText(_translate("IInsertPatient_2", "Subscriber", None))
        self.label_11.setText(_translate("IInsertPatient_2", "Relation", None))
        self.label_12.setText(_translate("IInsertPatient_2", "Address", None))
        self.label_13.setText(_translate("IInsertPatient_2", "DDB", None))
        self.label_14.setText(_translate("IInsertPatient_2", "Group", None))
        self.label_15.setText(_translate("IInsertPatient_2", "Reg. No.", None))
        self.label_16.setText(_translate("IInsertPatient_2", "Living Well #", None))
        self.label_17.setText(_translate("IInsertPatient_2", "Name", None))
        self.label_18.setText(_translate("IInsertPatient_2", "Gender", None))
        self.label_19.setText(_translate("IInsertPatient_2", "Phone", None))
        self.label_20.setText(_translate("IInsertPatient_2", "TRN", None))
        self.label_21.setText(_translate("IInsertPatient_2", "Insurance", None))
        self.label_22.setText(_translate("IInsertPatient_2", "NHF No", None))
        self.label_25.setText(_translate("IInsertPatient_2", "Balance", None))
        self.label_28.setText(_translate("IInsertPatient_2", "Address", None))
        self.label_29.setText(_translate("IInsertPatient_2", "DOB", None))
        self.IGender.setItemText(0, _translate("IInsertPatient_2", "F", None))
        self.IGender.setItemText(1, _translate("IInsertPatient_2", "H", None))
        self.IInsurance.setItemText(0, _translate("IInsertPatient_2", "<N/A>", None))
        self.label_33.setText(_translate("IInsertPatient_2", "Patient", None))
        self.IFlag.setText(_translate("IInsertPatient_2", "Alert Flag", None))
        self.IOk.setText(_translate("IInsertPatient_2", "Ok", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    IInsertPatient_2 = QtGui.QDialog()
    ui = Ui_IInsertPatient_2()
    ui.setupUi(IInsertPatient_2)
    IInsertPatient_2.show()
    sys.exit(app.exec_())

