# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\achill123\Desktop\PHARMAPROJECT\NewStuff.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1324, 897)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1308, 877))
        self.tabWidget.setStyleSheet(_fromUtf8("background-color: rgb(240, 240, 240);"))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Dispensary_tab = QtGui.QWidget()
        self.Dispensary_tab.setObjectName(_fromUtf8("Dispensary_tab"))
        self.BPrint = QtGui.QPushButton(self.Dispensary_tab)
        self.BPrint.setGeometry(QtCore.QRect(658, 761, 321, 28))
        self.BPrint.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BPrint.setStyleSheet(_fromUtf8("background-color: rgb(230, 230, 230);"))
        self.BPrint.setObjectName(_fromUtf8("BPrint"))
        self.BNext = QtGui.QPushButton(self.Dispensary_tab)
        self.BNext.setGeometry(QtCore.QRect(982, 761, 321, 28))
        self.BNext.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BNext.setStyleSheet(_fromUtf8("background-color: rgb(230, 230, 230);"))
        self.BNext.setObjectName(_fromUtf8("BNext"))
        self.BLookup = QtGui.QPushButton(self.Dispensary_tab)
        self.BLookup.setGeometry(QtCore.QRect(335, 791, 321, 28))
        self.BLookup.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BLookup.setStyleSheet(_fromUtf8("background-color: rgb(230, 230, 230);"))
        self.BLookup.setObjectName(_fromUtf8("BLookup"))
        self.BCalculator = QtGui.QPushButton(self.Dispensary_tab)
        self.BCalculator.setGeometry(QtCore.QRect(335, 731, 321, 28))
        self.BCalculator.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BCalculator.setStyleSheet(_fromUtf8("background-color: rgb(230, 230, 230);"))
        self.BCalculator.setObjectName(_fromUtf8("BCalculator"))
        self.groupBox_2 = QtGui.QGroupBox(self.Dispensary_tab)
        self.groupBox_2.setGeometry(QtCore.QRect(880, 420, 411, 271))
        self.groupBox_2.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.groupBox_2.setStyleSheet(_fromUtf8("background-color: rgb(230, 230, 230);"))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(22, 21, 27, 16))
        self.label_4.setStyleSheet(_fromUtf8("color: rgb(154, 0, 0);"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(22, 50, 23, 16))
        self.label_5.setStyleSheet(_fromUtf8("color:red"))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(22, 79, 76, 16))
        self.label_6.setStyleSheet(_fromUtf8("color: rgb(154, 0, 0);"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(22, 108, 28, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(22, 137, 40, 16))
        self.label_8.setStyleSheet(_fromUtf8("color: rgb(154, 0, 0);"))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(22, 166, 92, 16))
        self.label_9.setStyleSheet(_fromUtf8("color: rgb(0, 0, 166);"))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(22, 195, 48, 16))
        self.label_10.setStyleSheet(_fromUtf8("color:red"))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.RTotal = QtGui.QLineEdit(self.groupBox_2)
        self.RTotal.setGeometry(QtCore.QRect(121, 21, 137, 22))
        self.RTotal.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.RTotal.setStyleSheet(_fromUtf8("background-color:white;\n"
"color: rgb(154, 0, 0);"))
        self.RTotal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.RTotal.setObjectName(_fromUtf8("RTotal"))
        self.RNhf = QtGui.QLineEdit(self.groupBox_2)
        self.RNhf.setGeometry(QtCore.QRect(121, 50, 137, 22))
        self.RNhf.setStyleSheet(_fromUtf8("background-color:white;\n"
"color:red"))
        self.RNhf.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.RNhf.setObjectName(_fromUtf8("RNhf"))
        self.RDrug = QtGui.QLineEdit(self.groupBox_2)
        self.RDrug.setGeometry(QtCore.QRect(121, 79, 137, 22))
        self.RDrug.setStyleSheet(_fromUtf8("background-color:white;\n"
"color: rgb(154, 0, 0);"))
        self.RDrug.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.RDrug.setObjectName(_fromUtf8("RDrug"))
        self.R31 = QtGui.QLineEdit(self.groupBox_2)
        self.R31.setGeometry(QtCore.QRect(122, 109, 31, 22))
        self.R31.setStyleSheet(_fromUtf8("background-color:white"))
        self.R31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.R31.setObjectName(_fromUtf8("R31"))
        self.R32 = QtGui.QLineEdit(self.groupBox_2)
        self.R32.setGeometry(QtCore.QRect(160, 109, 98, 22))
        self.R32.setStyleSheet(_fromUtf8("background-color:white"))
        self.R32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.R32.setObjectName(_fromUtf8("R32"))
        self.RCo = QtGui.QLineEdit(self.groupBox_2)
        self.RCo.setGeometry(QtCore.QRect(121, 137, 137, 22))
        self.RCo.setStyleSheet(_fromUtf8("background-color:white;\n"
"color: rgb(0, 0, 166);"))
        self.RCo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.RCo.setObjectName(_fromUtf8("RCo"))
        self.RAgreed = QtGui.QLineEdit(self.groupBox_2)
        self.RAgreed.setGeometry(QtCore.QRect(121, 166, 137, 22))
        self.RAgreed.setStyleSheet(_fromUtf8("background-color:rgb(75, 226, 226);\n"
"alternate-background-color: rgb(75, 226, 226);\n"
""))
        self.RAgreed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.RAgreed.setObjectName(_fromUtf8("RAgreed"))
        self.RDiscount = QtGui.QComboBox(self.groupBox_2)
        self.RDiscount.setGeometry(QtCore.QRect(121, 195, 68, 22))
        self.RDiscount.setStyleSheet(_fromUtf8("background-color:white;\n"
"color:red"))
        self.RDiscount.setObjectName(_fromUtf8("RDiscount"))
        self.RDiscount.addItem(_fromUtf8(""))
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(221, 200, 53, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(60, 230, 311, 31))
        self.label_12.setStyleSheet(_fromUtf8("font: 75 12pt bold \"Calibri Light\";\n"
""))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.BQuote = QtGui.QPushButton(self.Dispensary_tab)
        self.BQuote.setGeometry(QtCore.QRect(658, 791, 321, 28))
        self.BQuote.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BQuote.setStyleSheet(_fromUtf8("background-color: rgb(230, 230, 230);"))
        self.BQuote.setObjectName(_fromUtf8("BQuote"))
        self.line = QtGui.QFrame(self.Dispensary_tab)
        self.line.setGeometry(QtCore.QRect(0, 710, 1301, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.BInternet = QtGui.QPushButton(self.Dispensary_tab)
        self.BInternet.setGeometry(QtCore.QRect(658, 731, 321, 28))
        self.BInternet.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BInternet.setStyleSheet(_fromUtf8("background-color: rgb(230, 230, 230);"))
        self.BInternet.setObjectName(_fromUtf8("BInternet"))
        self.Label1 = QtGui.QLabel(self.Dispensary_tab)
        self.Label1.setGeometry(QtCore.QRect(0, 0, 1311, 31))
        self.Label1.setStyleSheet(_fromUtf8("background-color: rgb(230, 230, 230);"))
        self.Label1.setText(_fromUtf8(""))
        self.Label1.setObjectName(_fromUtf8("Label1"))
        self.groupBox = QtGui.QGroupBox(self.Dispensary_tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 420, 411, 271))
        self.groupBox.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setStyleSheet(_fromUtf8("background-color: rgb(230, 230, 230);\n"
"font:bold"))
        self.groupBox.setFlat(True)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(11, 41, 41, 16))
        self.label.setStyleSheet(_fromUtf8("color: rgb(0, 0, 166);\n"
"font: 90 8pt \"MS Shell Dlg 2\";"))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(11, 110, 51, 16))
        self.label_2.setStyleSheet(_fromUtf8("color: rgb(0, 0, 166);\n"
"font: 90 8pt \"MS Shell Dlg 2\";"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(11, 178, 51, 16))
        self.label_3.setStyleSheet(_fromUtf8("color: rgb(0, 0, 166);\n"
"font: 90 8pt \"MS Shell Dlg 2\";"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.PDoctor2 = QtGui.QLineEdit(self.groupBox)
        self.PDoctor2.setGeometry(QtCore.QRect(60, 110, 221, 22))
        self.PDoctor2.setStyleSheet(_fromUtf8("background-color:white"))
        self.PDoctor2.setObjectName(_fromUtf8("PDoctor2"))
        self.PDoctor1 = QtGui.QLineEdit(self.groupBox)
        self.PDoctor1.setGeometry(QtCore.QRect(60, 90, 221, 22))
        self.PDoctor1.setStyleSheet(_fromUtf8("background-color:white;\n"
"border-color: rgb(0, 0, 255);"))
        self.PDoctor1.setObjectName(_fromUtf8("PDoctor1"))
        self.PName = QtGui.QLineEdit(self.groupBox)
        self.PName.setGeometry(QtCore.QRect(60, 40, 221, 22))
        self.PName.setStyleSheet(_fromUtf8("background-color:white"))
        self.PName.setObjectName(_fromUtf8("PName"))
        self.PSource = QtGui.QComboBox(self.groupBox)
        self.PSource.setGeometry(QtCore.QRect(60, 177, 221, 22))
        self.PSource.setStyleSheet(_fromUtf8("background-color:white"))
        self.PSource.setObjectName(_fromUtf8("PSource"))
        self.PSource.addItem(_fromUtf8(""))
        self.PSource.addItem(_fromUtf8(""))
        self.groupBox_3 = QtGui.QGroupBox(self.Dispensary_tab)
        self.groupBox_3.setGeometry(QtCore.QRect(445, 420, 411, 271))
        self.groupBox_3.setStyleSheet(_fromUtf8("background-color: rgb(230, 230, 230);"))
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.RxN = QtGui.QLineEdit(self.groupBox_3)
        self.RxN.setGeometry(QtCore.QRect(100, 10, 134, 22))
        self.RxN.setStyleSheet(_fromUtf8("background-color: white;\n"
"color:white;\n"
"font: bold;\n"
""))
        self.RxN.setText(_fromUtf8(""))
        self.RxN.setObjectName(_fromUtf8("RxN"))
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(57, 12, 36, 16))
        self.label_13.setStyleSheet(_fromUtf8("font:bold"))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.pushButton_17 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_17.setGeometry(QtCore.QRect(240, 7, 93, 28))
        self.pushButton_17.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.label_14 = QtGui.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(82, 130, 271, 71))
        self.label_14.setStyleSheet(_fromUtf8("color: rgb(104, 104, 104);\n"
"font: 75 italic 10pt \\\"8514oem\\\";"))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.MyDate = QtGui.QLabel(self.Dispensary_tab)
        self.MyDate.setGeometry(QtCore.QRect(1140, 5, 151, 16))
        self.MyDate.setStyleSheet(_fromUtf8("color:rgb(163, 8, 29)"))
        self.MyDate.setObjectName(_fromUtf8("MyDate"))
        self.BClose = QtGui.QPushButton(self.Dispensary_tab)
        self.BClose.setGeometry(QtCore.QRect(982, 731, 321, 28))
        self.BClose.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BClose.setStyleSheet(_fromUtf8("background-color: rgb(230, 230, 230);"))
        self.BClose.setObjectName(_fromUtf8("BClose"))
        self.MainTableX = QtGui.QTableWidget(self.Dispensary_tab)
        self.MainTableX.setGeometry(QtCore.QRect(0, 30, 1301, 381))
        self.MainTableX.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.MainTableX.setStyleSheet(_fromUtf8("background-color:white;"))
        self.MainTableX.setFrameShadow(QtGui.QFrame.Sunken)
        self.MainTableX.setLineWidth(1)
        self.MainTableX.setMidLineWidth(0)
        self.MainTableX.setObjectName(_fromUtf8("MainTableX"))
        self.MainTableX.setColumnCount(16)
        self.MainTableX.setRowCount(11)
        item = QtGui.QTableWidgetItem()
        self.MainTableX.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.MainTableX.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.MainTableX.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.MainTableX.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.MainTableX.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.MainTableX.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.MainTableX.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.MainTableX.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.MainTableX.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.MainTableX.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.MainTableX.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.MainTableX.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.MainTableX.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.MainTableX.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.MainTableX.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.MainTableX.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.MainTableX.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.MainTableX.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.MainTableX.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.MainTableX.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.MainTableX.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.MainTableX.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.MainTableX.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.MainTableX.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.MainTableX.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.MainTableX.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.MainTableX.setHorizontalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.MainTableX.setItem(0, 0, item)
        self.MainTableX.horizontalHeader().setCascadingSectionResizes(False)
        self.MainTableX.horizontalHeader().setSortIndicatorShown(False)
        self.BLabel = QtGui.QPushButton(self.Dispensary_tab)
        self.BLabel.setGeometry(QtCore.QRect(11, 791, 321, 28))
        self.BLabel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BLabel.setStyleSheet(_fromUtf8("background-color: rgb(230, 230, 230);"))
        self.BLabel.setObjectName(_fromUtf8("BLabel"))
        self.BDrugs = QtGui.QPushButton(self.Dispensary_tab)
        self.BDrugs.setGeometry(QtCore.QRect(11, 761, 321, 28))
        self.BDrugs.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BDrugs.setStyleSheet(_fromUtf8("background-color: rgb(230, 230, 230);"))
        self.BDrugs.setObjectName(_fromUtf8("BDrugs"))
        self.BPatient = QtGui.QPushButton(self.Dispensary_tab)
        self.BPatient.setGeometry(QtCore.QRect(335, 761, 321, 28))
        self.BPatient.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BPatient.setStyleSheet(_fromUtf8("background-color: rgb(230, 230, 230);"))
        self.BPatient.setObjectName(_fromUtf8("BPatient"))
        self.BReversal = QtGui.QPushButton(self.Dispensary_tab)
        self.BReversal.setGeometry(QtCore.QRect(11, 731, 321, 28))
        self.BReversal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BReversal.setStyleSheet(_fromUtf8("background-color: rgb(230, 230, 230);"))
        self.BReversal.setFlat(False)
        self.BReversal.setObjectName(_fromUtf8("BReversal"))
        self.BDelete = QtGui.QPushButton(self.Dispensary_tab)
        self.BDelete.setGeometry(QtCore.QRect(982, 791, 321, 28))
        self.BDelete.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BDelete.setStyleSheet(_fromUtf8("background-color: rgb(230, 230, 230);"))
        self.BDelete.setObjectName(_fromUtf8("BDelete"))
        self.tabWidget.addTab(self.Dispensary_tab, _fromUtf8(""))
        self.Sales_Tab = QtGui.QWidget()
        self.Sales_Tab.setObjectName(_fromUtf8("Sales_Tab"))
        self.tableWidget = QtGui.QTableWidget(self.Sales_Tab)
        self.tableWidget.setGeometry(QtCore.QRect(5, 70, 1301, 581))
        self.tableWidget.setStyleSheet(_fromUtf8("background-color:white;\n"
""))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(20)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(17, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(18, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(19, item)
        self.tableWidget_2 = QtGui.QTableWidget(self.Sales_Tab)
        self.tableWidget_2.setGeometry(QtCore.QRect(300, 650, 701, 161))
        self.tableWidget_2.setStyleSheet(_fromUtf8(""))
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        self.tableWidget_2.setColumnCount(7)
        self.tableWidget_2.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        self.pushButton = QtGui.QPushButton(self.Sales_Tab)
        self.pushButton.setGeometry(QtCore.QRect(1208, 790, 93, 28))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.label_15 = QtGui.QLabel(self.Sales_Tab)
        self.label_15.setGeometry(QtCore.QRect(20, 14, 201, 41))
        self.label_15.setStyleSheet(_fromUtf8("color: rgb(104, 104, 104);\n"
"font: 87 10pt \"Arial Black\";"))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.groupBox_4 = QtGui.QGroupBox(self.Sales_Tab)
        self.groupBox_4.setGeometry(QtCore.QRect(820, 2, 481, 61))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.dateEdit = QtGui.QDateEdit(self.groupBox_4)
        self.dateEdit.setGeometry(QtCore.QRect(10, 24, 110, 22))
        self.dateEdit.setStyleSheet(_fromUtf8("background-color:white;"))
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.dateEdit_2 = QtGui.QDateEdit(self.groupBox_4)
        self.dateEdit_2.setGeometry(QtCore.QRect(160, 24, 110, 22))
        self.dateEdit_2.setStyleSheet(_fromUtf8("background-color:white;"))
        self.dateEdit_2.setObjectName(_fromUtf8("dateEdit_2"))
        self.label_16 = QtGui.QLabel(self.groupBox_4)
        self.label_16.setGeometry(QtCore.QRect(130, 26, 21, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.pushButton_2 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_2.setGeometry(QtCore.QRect(280, 20, 93, 28))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_3.setGeometry(QtCore.QRect(380, 20, 93, 28))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.tabWidget.addTab(self.Sales_Tab, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 10, 1281, 81))
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.label_17 = QtGui.QLabel(self.groupBox_5)
        self.label_17.setGeometry(QtCore.QRect(30, 27, 211, 16))
        self.label_17.setStyleSheet(_fromUtf8("color: rgb(104, 104, 104);\n"
"font: 87 10pt \"Arial Black\";"))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.pushButton_4 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_4.setGeometry(QtCore.QRect(1170, 20, 93, 28))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.label_18 = QtGui.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(30, 110, 53, 16))
        self.label_18.setStyleSheet(_fromUtf8("color:blue;\n"
"font:bold;"))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.comboBox = QtGui.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(88, 110, 161, 22))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.pushButton_5 = QtGui.QPushButton(self.tab)
        self.pushButton_5.setGeometry(QtCore.QRect(1190, 110, 93, 28))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.tableWidget_3 = QtGui.QTableWidget(self.tab)
        self.tableWidget_3.setGeometry(QtCore.QRect(10, 150, 1281, 641))
        self.tableWidget_3.setStyleSheet(_fromUtf8("background-color:white;"))
        self.tableWidget_3.setObjectName(_fromUtf8("tableWidget_3"))
        self.tableWidget_3.setColumnCount(13)
        self.tableWidget_3.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(12, item)
        self.label_19 = QtGui.QLabel(self.tab)
        self.label_19.setGeometry(QtCore.QRect(30, 800, 53, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.tab)
        self.label_20.setGeometry(QtCore.QRect(160, 800, 53, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.tab)
        self.label_21.setGeometry(QtCore.QRect(260, 800, 53, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1324, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuGfdgfd = QtGui.QMenu(self.menubar)
        self.menuGfdgfd.setObjectName(_fromUtf8("menuGfdgfd"))
        self.menuDf = QtGui.QMenu(self.menubar)
        self.menuDf.setObjectName(_fromUtf8("menuDf"))
        self.menuPoint_of_sale = QtGui.QMenu(self.menubar)
        self.menuPoint_of_sale.setObjectName(_fromUtf8("menuPoint_of_sale"))
        self.menuSetup = QtGui.QMenu(self.menubar)
        self.menuSetup.setObjectName(_fromUtf8("menuSetup"))
        self.menuInventory = QtGui.QMenu(self.menubar)
        self.menuInventory.setObjectName(_fromUtf8("menuInventory"))
        self.menuAccounting = QtGui.QMenu(self.menubar)
        self.menuAccounting.setObjectName(_fromUtf8("menuAccounting"))
        self.menuReport = QtGui.QMenu(self.menubar)
        self.menuReport.setObjectName(_fromUtf8("menuReport"))
        self.menuInternet = QtGui.QMenu(self.menubar)
        self.menuInternet.setObjectName(_fromUtf8("menuInternet"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSettings = QtGui.QAction(MainWindow)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionDispensary = QtGui.QAction(MainWindow)
        self.actionDispensary.setObjectName(_fromUtf8("actionDispensary"))
        self.menubar.addAction(self.menuGfdgfd.menuAction())
        self.menubar.addAction(self.menuDf.menuAction())
        self.menubar.addAction(self.menuPoint_of_sale.menuAction())
        self.menubar.addAction(self.menuSetup.menuAction())
        self.menubar.addAction(self.menuInventory.menuAction())
        self.menubar.addAction(self.menuAccounting.menuAction())
        self.menubar.addAction(self.menuReport.menuAction())
        self.menubar.addAction(self.menuInternet.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.BPrint.setText(_translate("MainWindow", "F6-Print", None))
        self.BNext.setText(_translate("MainWindow", "F8-Next", None))
        self.BLookup.setText(_translate("MainWindow", "F5-View Rx", None))
        self.BCalculator.setText(_translate("MainWindow", "Calculator", None))
        self.label_4.setText(_translate("MainWindow", "Total", None))
        self.label_5.setText(_translate("MainWindow", "NHF", None))
        self.label_6.setText(_translate("MainWindow", "Drug charges", None))
        self.label_7.setText(_translate("MainWindow", "3000", None))
        self.label_8.setText(_translate("MainWindow", "Co-pay", None))
        self.label_9.setText(_translate("MainWindow", "Agreed discount", None))
        self.label_10.setText(_translate("MainWindow", "Discount", None))
        self.RTotal.setText(_translate("MainWindow", "$0.00", None))
        self.RNhf.setText(_translate("MainWindow", "0", None))
        self.RDrug.setText(_translate("MainWindow", "$0.00", None))
        self.R31.setText(_translate("MainWindow", "0", None))
        self.R32.setText(_translate("MainWindow", "$0.00", None))
        self.RCo.setText(_translate("MainWindow", "$0.00", None))
        self.RAgreed.setText(_translate("MainWindow", "$0.00", None))
        self.RDiscount.setItemText(0, _translate("MainWindow", "0", None))
        self.label_11.setText(_translate("MainWindow", "$0.00", None))
        self.label_12.setText(_translate("MainWindow", "NHF Pays : $0.00 You pay $0.00", None))
        self.BQuote.setText(_translate("MainWindow", "F7-Quote", None))
        self.BInternet.setText(_translate("MainWindow", "Internet", None))
        self.groupBox.setTitle(_translate("MainWindow", "Patient", None))
        self.label.setText(_translate("MainWindow", "Name", None))
        self.label_2.setText(_translate("MainWindow", "Doctor", None))
        self.label_3.setText(_translate("MainWindow", "Source", None))
        self.PSource.setItemText(0, _translate("MainWindow", "Private", None))
        self.PSource.setItemText(1, _translate("MainWindow", "Public", None))
        self.label_13.setText(_translate("MainWindow", "Rx No", None))
        self.pushButton_17.setText(_translate("MainWindow", "New Script", None))
        self.label_14.setText(_translate("MainWindow", "The Automated Pharmacy", None))
        self.MyDate.setText(_translate("MainWindow", "Tue Jun  5 02:57:12 2018", None))
        self.BClose.setText(_translate("MainWindow", "Close", None))
        item = self.MainTableX.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Drug 1", None))
        item = self.MainTableX.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Drug 2", None))
        item = self.MainTableX.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Drug 3", None))
        item = self.MainTableX.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Drug 4", None))
        item = self.MainTableX.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Drug 5", None))
        item = self.MainTableX.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Drug 6", None))
        item = self.MainTableX.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "Drug 7", None))
        item = self.MainTableX.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "Drug 8", None))
        item = self.MainTableX.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "Drug 9", None))
        item = self.MainTableX.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "Drug 10", None))
        item = self.MainTableX.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "QTY", None))
        item = self.MainTableX.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "COST", None))
        item = self.MainTableX.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "INS", None))
        item = self.MainTableX.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "FEES", None))
        item = self.MainTableX.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "LABEL", None))
        item = self.MainTableX.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "DAYS", None))
        item = self.MainTableX.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "REFILLS", None))
        item = self.MainTableX.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "EXTENDED", None))
        item = self.MainTableX.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "TAX", None))
        item = self.MainTableX.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "NHF", None))
        item = self.MainTableX.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "VOID", None))
        item = self.MainTableX.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "PRINTED", None))
        item = self.MainTableX.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "OS", None))
        item = self.MainTableX.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "IND", None))
        item = self.MainTableX.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "DIAGC", None))
        item = self.MainTableX.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "DISCOUNT", None))
        __sortingEnabled = self.MainTableX.isSortingEnabled()
        self.MainTableX.setSortingEnabled(False)
        self.MainTableX.setSortingEnabled(__sortingEnabled)
        self.BLabel.setText(_translate("MainWindow", "F3-Label", None))
        self.BDrugs.setText(_translate("MainWindow", "F2-Drugs", None))
        self.BPatient.setText(_translate("MainWindow", "F4-Patient", None))
        self.BReversal.setText(_translate("MainWindow", "Reversal", None))
        self.BDelete.setText(_translate("MainWindow", "CTRL-F9-Delete Rx", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Dispensary_tab), _translate("MainWindow", "Dispensary", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "RECEIPT", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "SALEDATE", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "SALETIME", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "SUBTOTAL", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "TAX", None))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "DISCOUNT", None))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "SALETYPE", None))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "USR", None))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "EXEMPTED", None))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "PAYMENT", None))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "PAYMODE", None))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "NAME", None))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Address", None))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "CHARGEAc", None))
        item = self.tableWidget.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "CARDNUMBER", None))
        item = self.tableWidget.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "INVOICE", None))
        item = self.tableWidget.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "RXND", None))
        item = self.tableWidget.horizontalHeaderItem(17)
        item.setText(_translate("MainWindow", "BALANCE", None))
        item = self.tableWidget.horizontalHeaderItem(18)
        item.setText(_translate("MainWindow", "2 nd PAYMENT", None))
        item = self.tableWidget.horizontalHeaderItem(19)
        item.setText(_translate("MainWindow", "PAYMODE2", None))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "DESCRIPTION", None))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "QUANTITY", None))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "PRICE", None))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "DISCOUNT", None))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "TAX", None))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Receipt", None))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "STATUS", None))
        self.pushButton.setText(_translate("MainWindow", "Print", None))
        self.label_15.setText(_translate("MainWindow", "Sales history", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Range", None))
        self.label_16.setText(_translate("MainWindow", "To", None))
        self.pushButton_2.setText(_translate("MainWindow", "Refresh", None))
        self.pushButton_3.setText(_translate("MainWindow", "Close", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Sales_Tab), _translate("MainWindow", "Sales History", None))
        self.label_17.setText(_translate("MainWindow", "PURCHASE HISTORY", None))
        self.pushButton_4.setText(_translate("MainWindow", "Close", None))
        self.label_18.setText(_translate("MainWindow", "Product", None))
        self.pushButton_5.setText(_translate("MainWindow", "Print", None))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "SUPPLIER", None))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "PACKAGE", None))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "NUMBER", None))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "DATE", None))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "QUANTITY", None))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "COST", None))
        item = self.tableWidget_3.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "GCT", None))
        item = self.tableWidget_3.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "TAXED", None))
        item = self.tableWidget_3.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "LOTNO", None))
        item = self.tableWidget_3.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "EXPIRY", None))
        item = self.tableWidget_3.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "DISCOUNT", None))
        item = self.tableWidget_3.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "ITEM", None))
        item = self.tableWidget_3.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Prv Qty", None))
        self.label_19.setText(_translate("MainWindow", "Totals : ", None))
        self.label_20.setText(_translate("MainWindow", "Qty : ", None))
        self.label_21.setText(_translate("MainWindow", "Value : ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Purchase History", None))
        self.menuGfdgfd.setTitle(_translate("MainWindow", "Settings", None))
        self.menuDf.setTitle(_translate("MainWindow", "Dispensary", None))
        self.menuPoint_of_sale.setTitle(_translate("MainWindow", "Point of sale", None))
        self.menuSetup.setTitle(_translate("MainWindow", "Setup", None))
        self.menuInventory.setTitle(_translate("MainWindow", "Inventory", None))
        self.menuAccounting.setTitle(_translate("MainWindow", "Accounting", None))
        self.menuReport.setTitle(_translate("MainWindow", "Reports", None))
        self.menuInternet.setTitle(_translate("MainWindow", "Internet", None))
        self.menuTools.setTitle(_translate("MainWindow", "Tools", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionSettings.setText(_translate("MainWindow", "Settings", None))
        self.actionDispensary.setText(_translate("MainWindow", "Dispensary", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

