# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\achill123\Desktop\PHARMAPROJECT\Products.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ProductsForm(object):
    def setupUi(self, ProductsForm):
        ProductsForm.setObjectName(_fromUtf8("ProductsForm"))
        ProductsForm.resize(916, 843)
        ProductsForm.setStyleSheet(_fromUtf8("background-color: rgb(231, 231, 231);"))
        self.groupBox = QtGui.QGroupBox(ProductsForm)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 891, 51))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.AddProduct = QtGui.QPushButton(self.groupBox)
        self.AddProduct.setGeometry(QtCore.QRect(10, 10, 93, 28))
        self.AddProduct.setStyleSheet(_fromUtf8(""))
        self.AddProduct.setObjectName(_fromUtf8("AddProduct"))
        self.NewProduct = QtGui.QPushButton(self.groupBox)
        self.NewProduct.setGeometry(QtCore.QRect(110, 10, 93, 28))
        self.NewProduct.setStyleSheet(_fromUtf8(""))
        self.NewProduct.setObjectName(_fromUtf8("NewProduct"))
        self.ProductClose = QtGui.QPushButton(self.groupBox)
        self.ProductClose.setGeometry(QtCore.QRect(790, 10, 93, 28))
        self.ProductClose.setStyleSheet(_fromUtf8(""))
        self.ProductClose.setObjectName(_fromUtf8("ProductClose"))
        self.DeleteProduct = QtGui.QPushButton(self.groupBox)
        self.DeleteProduct.setGeometry(QtCore.QRect(210, 10, 93, 28))
        self.DeleteProduct.setStyleSheet(_fromUtf8(""))
        self.DeleteProduct.setObjectName(_fromUtf8("DeleteProduct"))
        self.groupBox_2 = QtGui.QGroupBox(ProductsForm)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 70, 891, 221))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 23, 51, 16))
        self.label.setStyleSheet(_fromUtf8("\n"
""))
        self.label.setObjectName(_fromUtf8("label"))
        self.ProductNumber = QtGui.QLineEdit(self.groupBox_2)
        self.ProductNumber.setGeometry(QtCore.QRect(66, 21, 137, 22))
        self.ProductNumber.setStyleSheet(_fromUtf8("background-color:white;"))
        self.ProductNumber.setObjectName(_fromUtf8("ProductNumber"))
        self.ProductType = QtGui.QGroupBox(self.groupBox_2)
        self.ProductType.setGeometry(QtCore.QRect(10, 70, 191, 141))
        self.ProductType.setObjectName(_fromUtf8("ProductType"))
        self.ProductStock = QtGui.QRadioButton(self.ProductType)
        self.ProductStock.setGeometry(QtCore.QRect(21, 29, 95, 20))
        self.ProductStock.setObjectName(_fromUtf8("ProductStock"))
        self.ProductNonStock = QtGui.QRadioButton(self.ProductType)
        self.ProductNonStock.setGeometry(QtCore.QRect(21, 64, 131, 20))
        self.ProductNonStock.setObjectName(_fromUtf8("ProductNonStock"))
        self.ProductService = QtGui.QRadioButton(self.ProductType)
        self.ProductService.setGeometry(QtCore.QRect(21, 99, 95, 20))
        self.ProductService.setObjectName(_fromUtf8("ProductService"))
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(660, 20, 71, 16))
        self.label_2.setStyleSheet(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(647, 71, 91, 16))
        self.label_3.setStyleSheet(_fromUtf8("\n"
""))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(670, 120, 53, 16))
        self.label_4.setStyleSheet(_fromUtf8(""))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(630, 170, 101, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.ProductDescription = QtGui.QLineEdit(self.groupBox_2)
        self.ProductDescription.setGeometry(QtCore.QRect(741, 21, 137, 22))
        self.ProductDescription.setStyleSheet(_fromUtf8("background-color:white;"))
        self.ProductDescription.setObjectName(_fromUtf8("ProductDescription"))
        self.ProductGeneric = QtGui.QLineEdit(self.groupBox_2)
        self.ProductGeneric.setGeometry(QtCore.QRect(741, 70, 137, 22))
        self.ProductGeneric.setStyleSheet(_fromUtf8("background-color:white;"))
        self.ProductGeneric.setObjectName(_fromUtf8("ProductGeneric"))
        self.ProductSupplier = QtGui.QLineEdit(self.groupBox_2)
        self.ProductSupplier.setGeometry(QtCore.QRect(741, 119, 137, 22))
        self.ProductSupplier.setStyleSheet(_fromUtf8("background-color:white;"))
        self.ProductSupplier.setObjectName(_fromUtf8("ProductSupplier"))
        self.ProductAlternate = QtGui.QLineEdit(self.groupBox_2)
        self.ProductAlternate.setGeometry(QtCore.QRect(741, 168, 137, 22))
        self.ProductAlternate.setStyleSheet(_fromUtf8("background-color:white;"))
        self.ProductAlternate.setObjectName(_fromUtf8("ProductAlternate"))
        self.tabWidget = QtGui.QTabWidget(ProductsForm)
        self.tabWidget.setGeometry(QtCore.QRect(10, 300, 891, 531))
        self.tabWidget.setStyleSheet(_fromUtf8("background-color: rgb(239, 239, 239);"))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.Quantity = QtGui.QGroupBox(self.tab)
        self.Quantity.setGeometry(QtCore.QRect(10, 10, 861, 121))
        self.Quantity.setStyleSheet(_fromUtf8("color:rgb(16, 31, 166);\n"
"background-color: rgb(239, 239, 239);"))
        self.Quantity.setObjectName(_fromUtf8("Quantity"))
        self.QHand = QtGui.QLineEdit(self.Quantity)
        self.QHand.setGeometry(QtCore.QRect(80, 30, 113, 22))
        self.QHand.setStyleSheet(_fromUtf8("background-color:white;"))
        self.QHand.setObjectName(_fromUtf8("QHand"))
        self.QFull = QtGui.QLineEdit(self.Quantity)
        self.QFull.setGeometry(QtCore.QRect(80, 60, 113, 22))
        self.QFull.setStyleSheet(_fromUtf8("background-color:white;"))
        self.QFull.setObjectName(_fromUtf8("QFull"))
        self.QLoose = QtGui.QLineEdit(self.Quantity)
        self.QLoose.setGeometry(QtCore.QRect(80, 90, 113, 22))
        self.QLoose.setStyleSheet(_fromUtf8("background-color:white;"))
        self.QLoose.setObjectName(_fromUtf8("QLoose"))
        self.label_6 = QtGui.QLabel(self.Quantity)
        self.label_6.setGeometry(QtCore.QRect(20, 30, 53, 16))
        self.label_6.setStyleSheet(_fromUtf8("color:rgb(16, 31, 166);"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.Quantity)
        self.label_7.setGeometry(QtCore.QRect(31, 60, 31, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.Quantity)
        self.label_8.setGeometry(QtCore.QRect(27, 90, 53, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.QMax = QtGui.QLineEdit(self.Quantity)
        self.QMax.setGeometry(QtCore.QRect(415, 90, 113, 22))
        self.QMax.setStyleSheet(_fromUtf8("background-color:white;"))
        self.QMax.setObjectName(_fromUtf8("QMax"))
        self.label_9 = QtGui.QLabel(self.Quantity)
        self.label_9.setGeometry(QtCore.QRect(325, 60, 81, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.QSize = QtGui.QLineEdit(self.Quantity)
        self.QSize.setGeometry(QtCore.QRect(415, 60, 113, 22))
        self.QSize.setStyleSheet(_fromUtf8("background-color:white;"))
        self.QSize.setObjectName(_fromUtf8("QSize"))
        self.label_10 = QtGui.QLabel(self.Quantity)
        self.label_10.setGeometry(QtCore.QRect(346, 90, 53, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.Quantity)
        self.label_11.setGeometry(QtCore.QRect(312, 30, 101, 16))
        self.label_11.setStyleSheet(_fromUtf8("color:rgb(16, 31, 166);"))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.QUnits = QtGui.QComboBox(self.Quantity)
        self.QUnits.setGeometry(QtCore.QRect(415, 30, 111, 22))
        self.QUnits.setObjectName(_fromUtf8("QUnits"))
        self.QUnits.addItem(_fromUtf8(""))
        self.QBackOrder = QtGui.QLineEdit(self.Quantity)
        self.QBackOrder.setGeometry(QtCore.QRect(700, 90, 113, 22))
        self.QBackOrder.setStyleSheet(_fromUtf8("background-color:white;"))
        self.QBackOrder.setObjectName(_fromUtf8("QBackOrder"))
        self.label_12 = QtGui.QLabel(self.Quantity)
        self.label_12.setGeometry(QtCore.QRect(625, 60, 71, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.QReorderLvl = QtGui.QLineEdit(self.Quantity)
        self.QReorderLvl.setGeometry(QtCore.QRect(700, 30, 113, 22))
        self.QReorderLvl.setStyleSheet(_fromUtf8("background-color:white;"))
        self.QReorderLvl.setObjectName(_fromUtf8("QReorderLvl"))
        self.QReorderQty = QtGui.QLineEdit(self.Quantity)
        self.QReorderQty.setGeometry(QtCore.QRect(700, 60, 113, 22))
        self.QReorderQty.setStyleSheet(_fromUtf8("background-color:white;"))
        self.QReorderQty.setObjectName(_fromUtf8("QReorderQty"))
        self.label_13 = QtGui.QLabel(self.Quantity)
        self.label_13.setGeometry(QtCore.QRect(630, 90, 61, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.Quantity)
        self.label_14.setGeometry(QtCore.QRect(625, 30, 71, 16))
        self.label_14.setStyleSheet(_fromUtf8("color:rgb(16, 31, 166);"))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 135, 861, 151))
        self.groupBox_5.setStyleSheet(_fromUtf8("color: rgb(170, 0, 0);\n"
"background-color: rgb(239, 239, 239);"))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.label_15 = QtGui.QLabel(self.groupBox_5)
        self.label_15.setGeometry(QtCore.QRect(27, 20, 53, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.groupBox_5)
        self.label_16.setGeometry(QtCore.QRect(19, 50, 53, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.groupBox_5)
        self.label_17.setGeometry(QtCore.QRect(10, 80, 61, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.groupBox_5)
        self.label_18.setGeometry(QtCore.QRect(10, 110, 71, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.PriceCost = QtGui.QLineEdit(self.groupBox_5)
        self.PriceCost.setGeometry(QtCore.QRect(81, 19, 111, 22))
        self.PriceCost.setStyleSheet(_fromUtf8("background-color:white;"))
        self.PriceCost.setObjectName(_fromUtf8("PriceCost"))
        self.PriceMarkup = QtGui.QLineEdit(self.groupBox_5)
        self.PriceMarkup.setGeometry(QtCore.QRect(81, 49, 111, 22))
        self.PriceMarkup.setStyleSheet(_fromUtf8("background-color:white;"))
        self.PriceMarkup.setObjectName(_fromUtf8("PriceMarkup"))
        self.PriceEach = QtGui.QLineEdit(self.groupBox_5)
        self.PriceEach.setGeometry(QtCore.QRect(81, 79, 111, 22))
        self.PriceEach.setStyleSheet(_fromUtf8("background-color:white;"))
        self.PriceEach.setObjectName(_fromUtf8("PriceEach"))
        self.PriceWhole = QtGui.QLineEdit(self.groupBox_5)
        self.PriceWhole.setGeometry(QtCore.QRect(81, 109, 111, 22))
        self.PriceWhole.setStyleSheet(_fromUtf8("background-color:white;"))
        self.PriceWhole.setObjectName(_fromUtf8("PriceWhole"))
        self.PriceAvg = QtGui.QLineEdit(self.groupBox_5)
        self.PriceAvg.setGeometry(QtCore.QRect(415, 20, 113, 22))
        self.PriceAvg.setStyleSheet(_fromUtf8("background-color:white;"))
        self.PriceAvg.setObjectName(_fromUtf8("PriceAvg"))
        self.PriceLast = QtGui.QLineEdit(self.groupBox_5)
        self.PriceLast.setGeometry(QtCore.QRect(415, 49, 113, 22))
        self.PriceLast.setStyleSheet(_fromUtf8("background-color:white;"))
        self.PriceLast.setObjectName(_fromUtf8("PriceLast"))
        self.label_19 = QtGui.QLabel(self.groupBox_5)
        self.label_19.setGeometry(QtCore.QRect(350, 20, 53, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.groupBox_5)
        self.label_20.setGeometry(QtCore.QRect(350, 50, 53, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.groupBox_5)
        self.label_21.setGeometry(QtCore.QRect(615, 20, 91, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.groupBox_5)
        self.label_22.setGeometry(QtCore.QRect(628, 50, 71, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_23 = QtGui.QLabel(self.groupBox_5)
        self.label_23.setGeometry(QtCore.QRect(630, 80, 81, 16))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.PriceBreak = QtGui.QLineEdit(self.groupBox_5)
        self.PriceBreak.setGeometry(QtCore.QRect(700, 20, 113, 22))
        self.PriceBreak.setStyleSheet(_fromUtf8("background-color:white;"))
        self.PriceBreak.setObjectName(_fromUtf8("PriceBreak"))
        self.PriceBreak2 = QtGui.QLineEdit(self.groupBox_5)
        self.PriceBreak2.setGeometry(QtCore.QRect(700, 49, 113, 22))
        self.PriceBreak2.setStyleSheet(_fromUtf8("background-color:white;"))
        self.PriceBreak2.setObjectName(_fromUtf8("PriceBreak2"))
        self.PriceNhfBenefit = QtGui.QLineEdit(self.groupBox_5)
        self.PriceNhfBenefit.setGeometry(QtCore.QRect(700, 79, 113, 22))
        self.PriceNhfBenefit.setStyleSheet(_fromUtf8("background-color:white;"))
        self.PriceNhfBenefit.setObjectName(_fromUtf8("PriceNhfBenefit"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 290, 861, 80))
        self.groupBox_6.setStyleSheet(_fromUtf8("background-color: rgb(239, 239, 239);\n"
"color: rgb(70, 0, 106);"))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.TaxCode = QtGui.QGroupBox(self.groupBox_6)
        self.TaxCode.setGeometry(QtCore.QRect(10, 20, 371, 41))
        self.TaxCode.setTitle(_fromUtf8(""))
        self.TaxCode.setFlat(False)
        self.TaxCode.setObjectName(_fromUtf8("TaxCode"))
        self.ProductTaxable = QtGui.QRadioButton(self.TaxCode)
        self.ProductTaxable.setGeometry(QtCore.QRect(11, 11, 70, 20))
        self.ProductTaxable.setObjectName(_fromUtf8("ProductTaxable"))
        self.ProductZero = QtGui.QRadioButton(self.TaxCode)
        self.ProductZero.setGeometry(QtCore.QRect(130, 11, 91, 20))
        self.ProductZero.setObjectName(_fromUtf8("ProductZero"))
        self.ProductExempted = QtGui.QRadioButton(self.TaxCode)
        self.ProductExempted.setGeometry(QtCore.QRect(248, 11, 83, 20))
        self.ProductExempted.setObjectName(_fromUtf8("ProductExempted"))
        self.label_24 = QtGui.QLabel(self.groupBox_6)
        self.label_24.setGeometry(QtCore.QRect(590, 30, 91, 16))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.ProductSaleTax = QtGui.QLineEdit(self.groupBox_6)
        self.ProductSaleTax.setGeometry(QtCore.QRect(660, 30, 181, 22))
        self.ProductSaleTax.setStyleSheet(_fromUtf8("background-color:white;"))
        self.ProductSaleTax.setObjectName(_fromUtf8("ProductSaleTax"))
        self.groupBox_8 = QtGui.QGroupBox(self.tab)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 374, 861, 111))
        self.groupBox_8.setStyleSheet(_fromUtf8("background-color: rgb(239, 239, 239);\n"
"color: rgb(86, 0, 0);"))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.DiscontinueProduct = QtGui.QCheckBox(self.groupBox_8)
        self.DiscontinueProduct.setGeometry(QtCore.QRect(20, 20, 171, 20))
        self.DiscontinueProduct.setObjectName(_fromUtf8("DiscontinueProduct"))
        self.NhfCoverProduct = QtGui.QCheckBox(self.groupBox_8)
        self.NhfCoverProduct.setGeometry(QtCore.QRect(20, 60, 141, 20))
        self.NhfCoverProduct.setStyleSheet(_fromUtf8("font:bold"))
        self.NhfCoverProduct.setObjectName(_fromUtf8("NhfCoverProduct"))
        self.ProductBinNo = QtGui.QLineEdit(self.groupBox_8)
        self.ProductBinNo.setGeometry(QtCore.QRect(415, 20, 113, 22))
        self.ProductBinNo.setStyleSheet(_fromUtf8("background-color:white;"))
        self.ProductBinNo.setObjectName(_fromUtf8("ProductBinNo"))
        self.ProductMaxDosage = QtGui.QLineEdit(self.groupBox_8)
        self.ProductMaxDosage.setGeometry(QtCore.QRect(415, 60, 113, 22))
        self.ProductMaxDosage.setStyleSheet(_fromUtf8("background-color:white;"))
        self.ProductMaxDosage.setObjectName(_fromUtf8("ProductMaxDosage"))
        self.label_25 = QtGui.QLabel(self.groupBox_8)
        self.label_25.setGeometry(QtCore.QRect(360, 20, 53, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.groupBox_8)
        self.label_26.setGeometry(QtCore.QRect(332, 60, 81, 20))
        self.label_26.setStyleSheet(_fromUtf8("font:bold;"))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.ProductPrescription = QtGui.QGroupBox(self.groupBox_8)
        self.ProductPrescription.setGeometry(QtCore.QRect(660, 10, 181, 61))
        self.ProductPrescription.setObjectName(_fromUtf8("ProductPrescription"))
        self.PrescriptionYes = QtGui.QRadioButton(self.ProductPrescription)
        self.PrescriptionYes.setGeometry(QtCore.QRect(20, 30, 51, 20))
        self.PrescriptionYes.setObjectName(_fromUtf8("PrescriptionYes"))
        self.PrescriptionNo = QtGui.QRadioButton(self.ProductPrescription)
        self.PrescriptionNo.setGeometry(QtCore.QRect(110, 30, 51, 20))
        self.PrescriptionNo.setObjectName(_fromUtf8("PrescriptionNo"))
        self.label_27 = QtGui.QLabel(self.groupBox_8)
        self.label_27.setGeometry(QtCore.QRect(610, 83, 41, 16))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.ProductExpiry = QtGui.QComboBox(self.groupBox_8)
        self.ProductExpiry.setGeometry(QtCore.QRect(660, 80, 181, 22))
        self.ProductExpiry.setStyleSheet(_fromUtf8("background-color:white;"))
        self.ProductExpiry.setObjectName(_fromUtf8("ProductExpiry"))
        self.ProductExpiry.addItem(_fromUtf8(""))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.ProductGraphic = QtGui.QGraphicsView(self.tab_2)
        self.ProductGraphic.setGeometry(QtCore.QRect(10, 20, 481, 301))
        self.ProductGraphic.setObjectName(_fromUtf8("ProductGraphic"))
        self.label_28 = QtGui.QLabel(self.tab_2)
        self.label_28.setGeometry(QtCore.QRect(20, 350, 81, 16))
        self.label_28.setStyleSheet(_fromUtf8("color:red;\n"
"font: 11pt bold"))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.BarCodeProduct = QtGui.QLineEdit(self.tab_2)
        self.BarCodeProduct.setGeometry(QtCore.QRect(90, 348, 231, 22))
        self.BarCodeProduct.setStyleSheet(_fromUtf8("color:red;\n"
""))
        self.BarCodeProduct.setObjectName(_fromUtf8("BarCodeProduct"))
        self.label_29 = QtGui.QLabel(self.tab_2)
        self.label_29.setGeometry(QtCore.QRect(50, 390, 31, 16))
        self.label_29.setStyleSheet(_fromUtf8("font:9pt"))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.NdcProduct = QtGui.QLineEdit(self.tab_2)
        self.NdcProduct.setGeometry(QtCore.QRect(90, 390, 161, 22))
        self.NdcProduct.setObjectName(_fromUtf8("NdcProduct"))
        self.CodePostNetProduct = QtGui.QComboBox(self.tab_2)
        self.CodePostNetProduct.setGeometry(QtCore.QRect(90, 420, 161, 22))
        self.CodePostNetProduct.setObjectName(_fromUtf8("CodePostNetProduct"))
        self.CodePostNetProduct.addItem(_fromUtf8(""))
        self.ProductBarOption = QtGui.QGroupBox(self.tab_2)
        self.ProductBarOption.setGeometry(QtCore.QRect(610, 20, 231, 91))
        self.ProductBarOption.setObjectName(_fromUtf8("ProductBarOption"))
        self.ProductBarNumber = QtGui.QRadioButton(self.ProductBarOption)
        self.ProductBarNumber.setGeometry(QtCore.QRect(20, 30, 121, 20))
        self.ProductBarNumber.setObjectName(_fromUtf8("ProductBarNumber"))
        self.ProductBarNumber_2 = QtGui.QRadioButton(self.ProductBarOption)
        self.ProductBarNumber_2.setGeometry(QtCore.QRect(20, 61, 95, 20))
        self.ProductBarNumber_2.setObjectName(_fromUtf8("ProductBarNumber_2"))
        self.groupBox_11 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_11.setGeometry(QtCore.QRect(610, 230, 231, 91))
        self.groupBox_11.setTitle(_fromUtf8(""))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.IncludeProductName = QtGui.QCheckBox(self.groupBox_11)
        self.IncludeProductName.setGeometry(QtCore.QRect(20, 30, 111, 20))
        self.IncludeProductName.setObjectName(_fromUtf8("IncludeProductName"))
        self.IncludeProductNumber = QtGui.QCheckBox(self.groupBox_11)
        self.IncludeProductNumber.setGeometry(QtCore.QRect(20, 60, 121, 20))
        self.IncludeProductNumber.setObjectName(_fromUtf8("IncludeProductNumber"))
        self.PrintProduct = QtGui.QPushButton(self.tab_2)
        self.PrintProduct.setGeometry(QtCore.QRect(610, 400, 231, 41))
        self.PrintProduct.setStyleSheet(_fromUtf8("\n"
"font:bold;"))
        self.PrintProduct.setObjectName(_fromUtf8("PrintProduct"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.groupBox_12 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_12.setGeometry(QtCore.QRect(10, 10, 861, 221))
        self.groupBox_12.setTitle(_fromUtf8(""))
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.CheckProductUpdate = QtGui.QCheckBox(self.groupBox_12)
        self.CheckProductUpdate.setGeometry(QtCore.QRect(30, 30, 191, 20))
        self.CheckProductUpdate.setStyleSheet(_fromUtf8("color:red;\n"
"font:bold"))
        self.CheckProductUpdate.setObjectName(_fromUtf8("CheckProductUpdate"))
        self.label_30 = QtGui.QLabel(self.groupBox_12)
        self.label_30.setGeometry(QtCore.QRect(530, 30, 53, 16))
        self.label_30.setStyleSheet(_fromUtf8("font:bold;"))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.groupBox_14 = QtGui.QGroupBox(self.groupBox_12)
        self.groupBox_14.setGeometry(QtCore.QRect(570, 60, 261, 131))
        self.groupBox_14.setStyleSheet(_fromUtf8("color:rgb(140, 0, 0);"))
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.PurchaseDateLabel = QtGui.QLabel(self.groupBox_14)
        self.PurchaseDateLabel.setGeometry(QtCore.QRect(20, 40, 53, 16))
        self.PurchaseDateLabel.setObjectName(_fromUtf8("PurchaseDateLabel"))
        self.PurchaseQtyLabel = QtGui.QLabel(self.groupBox_14)
        self.PurchaseQtyLabel.setGeometry(QtCore.QRect(20, 80, 53, 16))
        self.PurchaseQtyLabel.setObjectName(_fromUtf8("PurchaseQtyLabel"))
        self.groupBox_15 = QtGui.QGroupBox(self.groupBox_12)
        self.groupBox_15.setGeometry(QtCore.QRect(270, 60, 261, 131))
        self.groupBox_15.setStyleSheet(_fromUtf8("color:rgb(64, 0, 194)"))
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.SaleDateLabel = QtGui.QLabel(self.groupBox_15)
        self.SaleDateLabel.setGeometry(QtCore.QRect(20, 40, 53, 16))
        self.SaleDateLabel.setObjectName(_fromUtf8("SaleDateLabel"))
        self.SaleQtyLabel = QtGui.QLabel(self.groupBox_15)
        self.SaleQtyLabel.setGeometry(QtCore.QRect(20, 80, 53, 16))
        self.SaleQtyLabel.setObjectName(_fromUtf8("SaleQtyLabel"))
        self.groupBox_13 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_13.setGeometry(QtCore.QRect(10, 240, 851, 251))
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.MovementTable = QtGui.QListWidget(self.groupBox_13)
        self.MovementTable.setGeometry(QtCore.QRect(20, 31, 821, 211))
        self.MovementTable.setStyleSheet(_fromUtf8("background-color:white;"))
        self.MovementTable.setObjectName(_fromUtf8("MovementTable"))
        item = QtGui.QListWidgetItem()
        self.MovementTable.addItem(item)
        item = QtGui.QListWidgetItem()
        self.MovementTable.addItem(item)
        item = QtGui.QListWidgetItem()
        self.MovementTable.addItem(item)
        item = QtGui.QListWidgetItem()
        self.MovementTable.addItem(item)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))

        self.retranslateUi(ProductsForm)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ProductsForm)

    def retranslateUi(self, ProductsForm):
        ProductsForm.setWindowTitle(_translate("ProductsForm", "Form", None))
        self.AddProduct.setText(_translate("ProductsForm", "Add", None))
        self.NewProduct.setText(_translate("ProductsForm", "New", None))
        self.ProductClose.setText(_translate("ProductsForm", "Close", None))
        self.DeleteProduct.setText(_translate("ProductsForm", "Delete all", None))
        self.label.setText(_translate("ProductsForm", "Number", None))
        self.ProductType.setTitle(_translate("ProductsForm", "Type", None))
        self.ProductStock.setText(_translate("ProductsForm", "Stock Item", None))
        self.ProductNonStock.setText(_translate("ProductsForm", "Non Stock Item", None))
        self.ProductService.setText(_translate("ProductsForm", "Service", None))
        self.label_2.setText(_translate("ProductsForm", "Description", None))
        self.label_3.setText(_translate("ProductsForm", "Generic Name", None))
        self.label_4.setText(_translate("ProductsForm", "Supplier", None))
        self.label_5.setText(_translate("ProductsForm", "Alternate supplier", None))
        self.Quantity.setTitle(_translate("ProductsForm", "Quantity", None))
        self.label_6.setText(_translate("ProductsForm", "On hand", None))
        self.label_7.setText(_translate("ProductsForm", "Full", None))
        self.label_8.setText(_translate("ProductsForm", "Loose", None))
        self.label_9.setText(_translate("ProductsForm", "Size / Units", None))
        self.label_10.setText(_translate("ProductsForm", "Max", None))
        self.label_11.setText(_translate("ProductsForm", "Units of measure", None))
        self.QUnits.setItemText(0, _translate("ProductsForm", "Each", None))
        self.label_12.setText(_translate("ProductsForm", "Reorder Qty", None))
        self.label_13.setText(_translate("ProductsForm", "BackOrder", None))
        self.label_14.setText(_translate("ProductsForm", "ReOrder lvl", None))
        self.groupBox_5.setTitle(_translate("ProductsForm", "Price", None))
        self.label_15.setText(_translate("ProductsForm", "Cost", None))
        self.label_16.setText(_translate("ProductsForm", "Markup", None))
        self.label_17.setText(_translate("ProductsForm", "Each price", None))
        self.label_18.setText(_translate("ProductsForm", "Whole price", None))
        self.label_19.setText(_translate("ProductsForm", "Avg cost", None))
        self.label_20.setText(_translate("ProductsForm", "Last cost", None))
        self.label_21.setText(_translate("ProductsForm", "Price break at", None))
        self.label_22.setText(_translate("ProductsForm", "Break price", None))
        self.label_23.setText(_translate("ProductsForm", "NHF benefit", None))
        self.groupBox_6.setTitle(_translate("ProductsForm", "Tax code", None))
        self.ProductTaxable.setText(_translate("ProductsForm", "Taxable", None))
        self.ProductZero.setText(_translate("ProductsForm", "Zero-Rated", None))
        self.ProductExempted.setText(_translate("ProductsForm", "Exempted", None))
        self.label_24.setText(_translate("ProductsForm", "Sale Tax %", None))
        self.groupBox_8.setTitle(_translate("ProductsForm", "Misc", None))
        self.DiscontinueProduct.setText(_translate("ProductsForm", "Discontinue this item ?", None))
        self.NhfCoverProduct.setText(_translate("ProductsForm", "NHF Covered item", None))
        self.label_25.setText(_translate("ProductsForm", "Bin No", None))
        self.label_26.setText(_translate("ProductsForm", "Max Dosage", None))
        self.ProductPrescription.setTitle(_translate("ProductsForm", "Prescription drug", None))
        self.PrescriptionYes.setText(_translate("ProductsForm", "Yes", None))
        self.PrescriptionNo.setText(_translate("ProductsForm", "No", None))
        self.label_27.setText(_translate("ProductsForm", "Expiry", None))
        self.ProductExpiry.setItemText(0, _translate("ProductsForm", "(none)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ProductsForm", "Details", None))
        self.label_28.setText(_translate("ProductsForm", "Barcode", None))
        self.BarCodeProduct.setText(_translate("ProductsForm", "8574121564", None))
        self.label_29.setText(_translate("ProductsForm", "NDC", None))
        self.CodePostNetProduct.setItemText(0, _translate("ProductsForm", "CodePostNet", None))
        self.ProductBarOption.setTitle(_translate("ProductsForm", "Option", None))
        self.ProductBarNumber.setText(_translate("ProductsForm", "Product number", None))
        self.ProductBarNumber_2.setText(_translate("ProductsForm", "Barcode", None))
        self.IncludeProductName.setText(_translate("ProductsForm", "Include name", None))
        self.IncludeProductNumber.setText(_translate("ProductsForm", "Include number", None))
        self.PrintProduct.setText(_translate("ProductsForm", "Print", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("ProductsForm", "Barcode", None))
        self.CheckProductUpdate.setText(_translate("ProductsForm", "Check to update stock", None))
        self.label_30.setText(_translate("ProductsForm", "Status", None))
        self.groupBox_14.setTitle(_translate("ProductsForm", "Purchases History", None))
        self.PurchaseDateLabel.setText(_translate("ProductsForm", "Date :", None))
        self.PurchaseQtyLabel.setText(_translate("ProductsForm", "Quantity", None))
        self.groupBox_15.setTitle(_translate("ProductsForm", "Sales History", None))
        self.SaleDateLabel.setText(_translate("ProductsForm", "Date :", None))
        self.SaleQtyLabel.setText(_translate("ProductsForm", "Quantity", None))
        self.groupBox_13.setTitle(_translate("ProductsForm", "Options", None))
        __sortingEnabled = self.MovementTable.isSortingEnabled()
        self.MovementTable.setSortingEnabled(False)
        item = self.MovementTable.item(0)
        item.setText(_translate("ProductsForm", "Option1", None))
        item = self.MovementTable.item(1)
        item.setText(_translate("ProductsForm", "Option2", None))
        item = self.MovementTable.item(2)
        item.setText(_translate("ProductsForm", "Option3", None))
        item = self.MovementTable.item(3)
        item.setText(_translate("ProductsForm", "Option4", None))
        self.MovementTable.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("ProductsForm", "Movement", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    ProductsForm = QtGui.QWidget()
    ui = Ui_ProductsForm()
    ui.setupUi(ProductsForm)
    ProductsForm.show()
    sys.exit(app.exec_())

